# Generated by Django 5.2.17 on 2026-08-10 10:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gateway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable internal identifier used by workflows.", unique=True
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                            ("openai_compatible", "OpenAI-compatible"),
                        ],
                        max_length=32,
                    ),
                ),
                ("base_url", models.URLField(blank=True)),
                ("enabled", models.BooleanField(default=False)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=60)),
                ("max_concurrency", models.PositiveSmallIntegerField(default=2)),
                (
                    "daily_budget_usd",
                    models.DecimalField(decimal_places=2, default=Decimal("10.00"), max_digits=10),
                ),
                ("extra_config", models.JSONField(blank=True, default=dict)),
                ("encrypted_api_key", models.TextField(blank=True, editable=False)),
                (
                    "api_key_fingerprint",
                    models.CharField(blank=True, editable=False, max_length=12),
                ),
                (
                    "health",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("pending", "Pending"),
                            ("healthy", "Healthy"),
                            ("unhealthy", "Unhealthy"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("priority", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("key", models.SlugField(unique=True)),
                ("provider_model_id", models.CharField(max_length=160)),
                ("enabled", models.BooleanField(default=False)),
                ("supports_structured_output", models.BooleanField(default=True)),
                ("supports_tools", models.BooleanField(default=True)),
                ("supports_streaming", models.BooleanField(default=True)),
                ("max_input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("max_output_tokens", models.PositiveIntegerField(default=8192)),
                ("default_parameters", models.JSONField(blank=True, default=dict)),
                (
                    "input_cost_per_million",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "output_cost_per_million",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "fallback_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallback_for",
                        to="ai_config.aimodel",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="ai_config.gateway",
                    ),
                ),
            ],
            options={
                "ordering": ("gateway__priority", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("key", models.SlugField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("purpose", models.CharField(max_length=160)),
                ("system_prompt", models.TextField()),
                ("published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("key", "-version"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("key", "version"), name="unique_prompt_version")
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("key", models.SlugField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("purpose", models.TextField()),
                ("allowed_tools", models.JSONField(blank=True, default=list)),
                ("input_schema", models.JSONField(blank=True, default=dict)),
                ("output_schema", models.JSONField(blank=True, default=dict)),
                ("max_iterations", models.PositiveSmallIntegerField(default=3)),
                ("max_output_tokens", models.PositiveIntegerField(default=8192)),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=120)),
                ("published", models.BooleanField(default=False)),
                (
                    "fallback_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fallback_agents",
                        to="ai_config.aimodel",
                    ),
                ),
                (
                    "primary_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_agents",
                        to="ai_config.aimodel",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agents",
                        to="ai_config.promptversion",
                    ),
                ),
            ],
            options={
                "ordering": ("key", "-version"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("key", models.SlugField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("supported_artifacts", models.JSONField(default=list)),
                (
                    "graph",
                    models.JSONField(
                        default=dict, help_text="Validated LangGraph node and edge definition."
                    ),
                ),
                ("max_repair_loops", models.PositiveSmallIntegerField(default=2)),
                ("token_budget", models.PositiveIntegerField(default=50000)),
                (
                    "cost_budget_usd",
                    models.DecimalField(decimal_places=2, default=Decimal("2.00"), max_digits=8),
                ),
                ("published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("key", "-version"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "version"), name="unique_workflow_version"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="aimodel",
            constraint=models.UniqueConstraint(
                fields=("gateway", "provider_model_id"), name="unique_gateway_model_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentdefinition",
            constraint=models.UniqueConstraint(
                fields=("key", "version"), name="unique_agent_version"
            ),
        ),
    ]
