// AUTO-GENERATED by Calyx news_pulse_calendar.py v1.0.
// Do not edit release timestamps by hand. Regenerate from the FXMacroData MCP.
#ifndef CALYX_NEWS_PULSE_TESTER_CALENDAR_MQH
#define CALYX_NEWS_PULSE_TESTER_CALENDAR_MQH

#define NP_TESTER_CALENDAR_COVERAGE_START_DATE 20260612
#define NP_TESTER_CALENDAR_COVERAGE_END_DATE 20260910
#define NP_TESTER_CALENDAR_EXPECTED_EVENTS 7

long NP_GENERATED_EVENT_UTC_EPOCHS[]={1781719200,1782995400,1784032200,1785348000,1786105800,1786537800,1788525000};
string NP_GENERATED_EVENT_KINDS[]={"FOMC","NFP","CPI","FOMC","NFP","CPI","NFP"};

string NP_GeneratedCalendarProvider() { return "FXMacroData MCP"; }
string NP_GeneratedCalendarHash() { return "57ef253ff6db4ab24aff1d70a231e48d8d33cb3e2c50c38235b1444bc97d44fd"; }
string NP_GeneratedCalendarFetchedAt() { return "2026-09-10T06:22:27.969149+00:00"; }
int NP_GeneratedCalendarEventCount() { return ArraySize(NP_GENERATED_EVENT_UTC_EPOCHS); }

#endif
