"""scan near-miss metrics

Revision ID: 29ea239512cf
Revises: 68f3333d8c9f
Create Date: 2026-09-29 14:19:56.519145
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import crypto_lab.infrastructure.db.base

revision: str = "29ea239512cf"
down_revision: str | None = "68f3333d8c9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pm_scan_run", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("best_ask_sum", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=True)
        )
        batch_op.add_column(
            sa.Column("best_bid_sum", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pm_scan_run", schema=None) as batch_op:
        batch_op.drop_column("best_bid_sum")
        batch_op.drop_column("best_ask_sum")

    # ### end Alembic commands ###
