"""initial schema

Revision ID: 68f3333d8c9f
Revises:
Create Date: 2026-09-29 14:09:57.832913
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import crypto_lab.infrastructure.db.base

revision: str = "68f3333d8c9f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("totp_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("totp_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=True),
        sa.Column("created_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.Column("last_login_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_user")),
        sa.UniqueConstraint("username", name=op.f("uq_admin_user_username")),
    )
    op.create_table(
        "api_credential",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("public_fields", sa.JSON(), nullable=False),
        sa.Column("secret_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("secret_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("hint", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.Column("rotated_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=True),
        sa.Column("last_test_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=True),
        sa.Column("last_test_ok", sa.Boolean(), nullable=True),
        sa.Column("last_test_message", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_credential")),
    )
    with op.batch_alter_table("api_credential", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_credential_provider"), ["provider"], unique=False)

    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=120), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_event_at"), ["at"], unique=False)

    op.create_table(
        "bot",
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=8), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("gate_passed", sa.Boolean(), nullable=False),
        sa.Column("kill_requested", sa.Boolean(), nullable=False),
        sa.Column("heartbeat_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("updated_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_bot")),
    )
    op.create_table(
        "pm_opportunity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("event_id", sa.String(length=32), nullable=False),
        sa.Column("condition_id", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("first_seen_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column("shares", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("capital", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("payout", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("fees", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("net_edge", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("best_net_edge", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("edge_pct", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("holds_to_resolution", sa.Boolean(), nullable=False),
        sa.Column("resolves_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=True),
        sa.Column("book_age_ms", sa.Integer(), nullable=False),
        sa.Column("legs", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_opportunity")),
    )
    with op.batch_alter_table("pm_opportunity", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pm_opportunity_active"), ["active"], unique=False)
        batch_op.create_index(batch_op.f("ix_pm_opportunity_fingerprint"), ["fingerprint"], unique=False)
        batch_op.create_index(batch_op.f("ix_pm_opportunity_first_seen_at"), ["first_seen_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_pm_opportunity_kind"), ["kind"], unique=False)

    op.create_table(
        "pm_paper_trade",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("opened_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=120), nullable=False),
        sa.Column("event_id", sa.String(length=32), nullable=False),
        sa.Column("condition_id", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("shares", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("capital", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("payout", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("fees", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("detected_edge", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("realized_pnl", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("resolves_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=True),
        sa.Column("settled_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=True),
        sa.Column("legs", sa.JSON(), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_paper_trade")),
    )
    with op.batch_alter_table("pm_paper_trade", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pm_paper_trade_fingerprint"), ["fingerprint"], unique=False)
        batch_op.create_index(batch_op.f("ix_pm_paper_trade_opened_at"), ["opened_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_pm_paper_trade_status"), ["status"], unique=False)

    op.create_table(
        "pm_scan_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.Column("finished_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("events_scanned", sa.Integer(), nullable=False),
        sa.Column("markets_scanned", sa.Integer(), nullable=False),
        sa.Column("books_fetched", sa.Integer(), nullable=False),
        sa.Column("stale_books", sa.Integer(), nullable=False),
        sa.Column("opportunities", sa.Integer(), nullable=False),
        sa.Column("paper_trades", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_scan_run")),
    )
    with op.batch_alter_table("pm_scan_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pm_scan_run_started_at"), ["started_at"], unique=False)

    op.create_table(
        "pm_wallet",
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("first_seen_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.Column("leaderboard_period", sa.String(length=8), nullable=False),
        sa.Column("leaderboard_rank", sa.Integer(), nullable=True),
        sa.Column("leaderboard_pnl", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=True),
        sa.Column("leaderboard_volume", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=True),
        sa.Column("tracked", sa.Boolean(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("stats_updated_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("address", name=op.f("pk_pm_wallet")),
    )
    with op.batch_alter_table("pm_wallet", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pm_wallet_tracked"), ["tracked"], unique=False)

    op.create_table(
        "pm_wallet_trade",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet", sa.String(length=42), nullable=False),
        sa.Column("tx_hash", sa.String(length=80), nullable=False),
        sa.Column("asset", sa.String(length=90), nullable=False),
        sa.Column("condition_id", sa.String(length=80), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("size", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("price", crypto_lab.infrastructure.db.base.DecimalText(length=40), nullable=False),
        sa.Column("outcome", sa.String(length=80), nullable=False),
        sa.Column("outcome_index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("event_slug", sa.String(length=200), nullable=False),
        sa.Column("at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_wallet_trade")),
        sa.UniqueConstraint("wallet", "tx_hash", "asset", "side", "size", name="uq_pm_wallet_trade_fill"),
    )
    with op.batch_alter_table("pm_wallet_trade", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pm_wallet_trade_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_pm_wallet_trade_wallet"), ["wallet"], unique=False)

    op.create_table(
        "admin_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("created_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.Column("expires_at", crypto_lab.infrastructure.db.base.UTCDateTime(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["admin_user.id"], name=op.f("fk_admin_session_user_id_admin_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_session")),
        sa.UniqueConstraint("token_digest", name=op.f("uq_admin_session_token_digest")),
    )
    with op.batch_alter_table("admin_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admin_session_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_session_user_id"))

    op.drop_table("admin_session")
    with op.batch_alter_table("pm_wallet_trade", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pm_wallet_trade_wallet"))
        batch_op.drop_index(batch_op.f("ix_pm_wallet_trade_at"))

    op.drop_table("pm_wallet_trade")
    with op.batch_alter_table("pm_wallet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pm_wallet_tracked"))

    op.drop_table("pm_wallet")
    with op.batch_alter_table("pm_scan_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pm_scan_run_started_at"))

    op.drop_table("pm_scan_run")
    with op.batch_alter_table("pm_paper_trade", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pm_paper_trade_status"))
        batch_op.drop_index(batch_op.f("ix_pm_paper_trade_opened_at"))
        batch_op.drop_index(batch_op.f("ix_pm_paper_trade_fingerprint"))

    op.drop_table("pm_paper_trade")
    with op.batch_alter_table("pm_opportunity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pm_opportunity_kind"))
        batch_op.drop_index(batch_op.f("ix_pm_opportunity_first_seen_at"))
        batch_op.drop_index(batch_op.f("ix_pm_opportunity_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_pm_opportunity_active"))

    op.drop_table("pm_opportunity")
    op.drop_table("bot")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_event_at"))

    op.drop_table("audit_event")
    with op.batch_alter_table("api_credential", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_credential_provider"))

    op.drop_table("api_credential")
    op.drop_table("admin_user")
    # ### end Alembic commands ###
