"""Build a source-receipted NFP/CPI/FOMC calendar, never a weekday heuristic."""
from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin
from zoneinfo import ZoneInfo

import requests
from bs4 import BeautifulSoup

ROOT=Path(__file__).resolve().parent
BEGIN='2021-09-05'
END='2026-09-05'
NY=ZoneInfo('America/New_York')
FED='https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm'

def event(kind,local,source,receipt):
    utc=local.astimezone(timezone.utc)
    return dict(kind=kind,release_local_et=local.isoformat(),release_utc=utc.isoformat().replace('+00:00','Z'),epoch=int(utc.timestamp()),source=source,receipt=receipt)

def fed_statement(url):
    response=requests.get(url,timeout=40);response.raise_for_status()
    soup=BeautifulSoup(response.text,'html.parser')
    text=soup.get_text(' ',strip=True)
    title=soup.find('h3',class_='title')
    title_text=title.get_text(' ',strip=True) if title else ''
    if 'Federal Reserve issues FOMC statement' not in title_text:
        return None
    when=re.search(r'For release at (\d{1,2}):(\d{2})\s*(a\.m\.|p\.m\.)\s*(EST|EDT)',text)
    assert when, (url,'missing official release time')
    date_string=re.search(r'monetary(\d{8})a.htm',url).group(1)
    hour=int(when[1])%12+(12 if when[3]=='p.m.' else 0)
    local=datetime.strptime(date_string,'%Y%m%d').replace(hour=hour,minute=int(when[2]),tzinfo=NY)
    assert local.tzname()==when[4], (url,'DST conflict')
    return event('FOMC',local,url,when[0])

def main():
    receipts=json.loads((ROOT/'bls-source-receipts.json').read_text())
    events=[]
    for row in receipts:
        match=re.search(r'([A-Za-z]+,\s+[A-Za-z]+\s+\d{1,2},\s+\d{4})\s+(\d{2}:\d{2}\s+[AP]M)\s+(Employment Situation|Consumer Price Index) for',row['line'])
        assert match,row
        local=datetime.strptime(match[1]+' '+match[2],'%A, %B %d, %Y %I:%M %p').replace(tzinfo=NY)
        events.append(event('NFP' if match[3]=='Employment Situation' else 'CPI',local,row['source'],row['line']))
    response=requests.get(FED,timeout=40);response.raise_for_status()
    soup=BeautifulSoup(response.text,'html.parser')
    links=sorted({urljoin(FED,a['href']) for a in soup.select('a[href]') if re.search(r'/monetary20\d{6}a.htm$',a['href'])})
    with ThreadPoolExecutor(max_workers=6) as pool:
        events.extend(row for row in pool.map(fed_statement,links) if row is not None)
    events=sorted({(row['epoch'],row['kind']):row for row in events if BEGIN<=row['release_utc'][:10]<END}.values(),key=lambda r:r['epoch'])
    assert all(row['kind'] in {'NFP','CPI','FOMC'} for row in events)
    assert len({row['epoch'] for row in events})==len(events)
    previous=json.loads((ROOT.parent/'News Pulse BTC Official 3Y Research 2026-09-11'/'OFFICIAL EVENT CALENDAR 3Y.json').read_text())
    previous_keys={(row['epoch'],row['kind']) for row in previous['events'] if BEGIN<=row['release_utc'][:10]<END}
    keys={(row['epoch'],row['kind']) for row in events}
    assert previous_keys<=keys, ('events missing versus previous official audit',previous_keys-keys)
    counts=Counter((row['release_utc'][:4],row['kind']) for row in events)
    # Full 2022-24 years must each have 12 CPI, 12 payroll and eight FOMC statements.
    for year in ('2022','2023','2024'):
        assert [counts[year,kind] for kind in ('NFP','CPI','FOMC')]==[12,12,8],(year,counts)
    canonical=json.dumps([(row['epoch'],row['kind']) for row in events],separators=(',',':'))
    digest=hashlib.sha256(canonical.encode()).hexdigest()
    manifest=dict(provider='Official BLS and Federal Reserve releases',from_date=BEGIN,to_exclusive=END,event_count=len(events),sha256=digest,generated_at=datetime.now(timezone.utc).isoformat(),events=events,counts_by_year={year:{kind:counts[year,kind] for kind in ('NFP','CPI','FOMC')} for year in sorted({r['release_utc'][:4] for r in events})},previous_official_overlap_events=len(previous_keys))
    (ROOT/'OFFICIAL CALENDAR.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
    epochs=','.join(str(row['epoch']) for row in events)
    kinds=','.join(json.dumps(row['kind']) for row in events)
    include=f'''// Generated by build_calendar.py from official-source receipts; tester only.
#ifndef CALYX_NEWS_PULSE_TESTER_CALENDAR_MQH
#define CALYX_NEWS_PULSE_TESTER_CALENDAR_MQH
#define NP_TESTER_CALENDAR_COVERAGE_START_DATE {BEGIN.replace('-','')}
#define NP_TESTER_CALENDAR_COVERAGE_END_DATE {END.replace('-','')}
#define NP_TESTER_CALENDAR_EXPECTED_EVENTS {len(events)}
long NP_GENERATED_EVENT_UTC_EPOCHS[]={{{epochs}}};
string NP_GENERATED_EVENT_KINDS[]={{{kinds}}};
string NP_GeneratedCalendarProvider() {{ return "Official BLS + Federal Reserve"; }}
string NP_GeneratedCalendarHash() {{ return "{digest}"; }}
string NP_GeneratedCalendarFetchedAt() {{ return "{manifest['generated_at']}"; }}
int NP_GeneratedCalendarEventCount() {{ return ArraySize(NP_GENERATED_EVENT_UTC_EPOCHS); }}
#endif
'''
    (ROOT/'NewsPulseTesterCalendar.mqh').write_text(include,encoding='utf-8')
    print(json.dumps({k:v for k,v in manifest.items() if k!='events'},indent=2))

if __name__=='__main__':main()
