"""Mechanically snapshot pure report parsing, independent of the mutable website.

No website files are imported or changed. Native MT5 trading logic is unchanged.
"""
import ast,hashlib,json,importlib.util
from data import ROOT,RAW,PACKAGE,save,sha

def extract(path,names):
    source=path.read_text(encoding='utf-8-sig');tree=ast.parse(source);nodes={n.name:n for n in tree.body if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef))}
    return [ast.get_source_segment(source,nodes[name]) for name in names]

def main():
    app=PACKAGE.parent/'EA store/app/mt5_evidence_jobs.py';raw=RAW/'run_raw.py'
    names=['_clean','_number','_percent_in_parentheses','_read_report','_metric','_native_metrics','_native_trades','_report_inputs','_same_setting']
    chunks=extract(app,names)+extract(raw,['parse_case'])
    header='''# Generated by freeze_parser.py: exact pure parsing functions, no app imports.
from __future__ import annotations
import html,re,json,csv
from collections import defaultdict
from datetime import datetime,timezone
from pathlib import Path
from typing import Any
import numpy as np
from data import NY,save,sha
TAG_RE=re.compile(r"<[^>]+>")
'''
    out=ROOT/'frozen_parser.py';out.write_text(header+'\n\n'.join(chunks)+'\n',encoding='utf-8')
    spec=importlib.util.spec_from_file_location('proof_parser',out);parser=importlib.util.module_from_spec(spec);spec.loader.exec_module(parser)
    captured={};parser.save=lambda path,obj:captured.update({str(path):obj})
    cases=[]
    for summary in sorted((ROOT/'native').glob('*/summary.json')):
        folder=summary.parent;old=json.loads((folder/'trades.json').read_text());stats=json.loads(summary.read_text());fresh=parser.parse_case(folder)
        assert captured[str(folder/'trades.json')]==old,folder.name
        for key in ('net_profit','commission','swap','profit_factor','trades','return_pct','max_drawdown_pct'):
            assert fresh[key]==stats[key],(folder.name,key)
        cases.append(folder.name)
    save(ROOT/'parser-isolation.json',dict(reason='Website catalog had external Git conflict markers during research. Snapshot only pure helpers to prevent unrelated app imports.',
        parser_sha256=sha(out),upstream_paths=[str(app),str(raw)],upstream_sha256=[sha(app),sha(raw)],
        function_sha256={name:hashlib.sha256(chunk.encode()).hexdigest() for name,chunk in zip(names+['parse_case'],chunks)},
        identical_completed_ledgers=cases,passed=True))
    print('PARSER SNAPSHOT VERIFIED',len(cases),'identical ledgers',flush=True)

if __name__=='__main__':main()
