# Generated by freeze_parser.py: exact pure parsing functions, no app imports.
from __future__ import annotations
import html,re,json,csv
from collections import defaultdict
from datetime import datetime,timezone
from pathlib import Path
from typing import Any
import numpy as np
from data import NY,save,sha
TAG_RE=re.compile(r"<[^>]+>")
def _clean(value: str) -> str:
    return html.unescape(TAG_RE.sub("", value)).replace("\xa0", " ").strip()

def _number(value: str) -> float:
    match = re.search(r"[-+]?\d[\d ]*(?:\.\d+)?", value.replace("%", ""))
    return float(match.group(0).replace(" ", "")) if match else 0.0

def _percent_in_parentheses(value: str) -> float:
    match = re.search(r"\(([-+]?\d+(?:\.\d+)?)%\)", value)
    return float(match.group(1)) if match else 0.0

def _read_report(path: Path) -> str:
    for encoding in ("utf-16", "utf-8-sig", "utf-8"):
        try:
            text = path.read_text(encoding=encoding)
        except UnicodeError:
            continue
        if "Initial Deposit" in text:
            return text
    return path.read_text(encoding="utf-8", errors="ignore")

def _metric(text: str, label: str) -> str:
    match = re.search(
        rf">\s*{re.escape(label)}:\s*</td>\s*<td[^>]*>\s*<b>(.*?)</b>",
        text,
        flags=re.I | re.S,
    )
    return _clean(match.group(1)) if match else ""

def _native_metrics(path: Path) -> dict[str, Any]:
    text = _read_report(path)
    initial = _number(_metric(text, "Initial Deposit"))
    net = _number(_metric(text, "Total Net Profit"))
    return {
        "initial_balance": round(initial, 2),
        "final_balance": round(initial + net, 2),
        "net_profit": round(net, 2),
        "return_pct": round(net / initial * 100, 2) if initial else 0.0,
        "profit_factor": round(_number(_metric(text, "Profit Factor")), 2),
        "win_rate_pct": round(_percent_in_parentheses(_metric(text, "Profit Trades (% of total)")), 2),
        "max_drawdown_pct": round(_percent_in_parentheses(_metric(text, "Equity Drawdown Maximal")), 2),
        "trades": int(_number(_metric(text, "Total Trades"))),
        "sharpe_ratio": round(_number(_metric(text, "Sharpe Ratio")), 2),
        "recovery_factor": round(_number(_metric(text, "Recovery Factor")), 2),
        "history_quality": _metric(text, "History Quality"),
    }

def _native_trades(path: Path, label: str) -> list[dict[str, Any]]:
    """Read completed positions directly from the MT5 Deals table.

    Pair exits with the opposite deal side, not just the symbol. News Pulse
    can hold a long and a short simultaneously. Within each side, entries are
    matched FIFO; entry costs are apportioned for partial closes.
    """
    text = _read_report(path)
    marker = text.lower().find("<b>deals</b>")
    if marker < 0:
        return []
    row_re = re.compile(r"<tr\b[^>]*>(.*?)</tr>", re.I | re.S)
    cell_re = re.compile(r"<td\b[^>]*>(.*?)</td>", re.I | re.S)
    entries: dict[tuple[str, str], list[dict[str, Any]]] = {}
    trades: list[dict[str, Any]] = []
    for row_html in row_re.findall(text[marker:]):
        cells = [_clean(cell) for cell in cell_re.findall(row_html)]
        if len(cells) < 13 or not re.fullmatch(r"\d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2}", cells[0]):
            continue
        symbol, deal_type, direction = cells[2], cells[3].lower(), cells[4].lower()
        if not symbol or deal_type not in {"buy", "sell"}:
            continue
        volume = _number(cells[5])
        price = _number(cells[6])
        commission = _number(cells[8])
        swap = _number(cells[9])
        profit = _number(cells[10])
        timestamp = cells[0].replace(".", "-", 2).replace(" ", "T", 1)
        if direction in {"in", "in/out"}:
            entries.setdefault((symbol, deal_type), []).append(
                {
                    "time": timestamp,
                    "type": deal_type,
                    "volume": volume,
                    "remaining": volume,
                    "price": price,
                    "commission": commission,
                    "swap": swap,
                    "profit": profit,
                    "comment": cells[12],
                }
            )
            if direction == "in":
                continue
        if direction not in {"out", "out by", "in/out"}:
            continue
        remaining_exit = volume
        entry_type = "sell" if deal_type == "buy" else "buy"
        queue = entries.get((symbol, entry_type), [])
        while remaining_exit > 1e-9 and queue:
            entry = queue[0]
            matched = min(remaining_exit, float(entry["remaining"]))
            share = matched / volume if volume > 0 else 1.0
            entry_share = matched / float(entry["volume"]) if float(entry["volume"]) > 0 else 1.0
            matched_commission = commission * share + float(entry["commission"]) * entry_share
            matched_swap = swap * share + float(entry["swap"]) * entry_share
            matched_gross_profit = profit * share + float(entry["profit"]) * entry_share
            net = matched_gross_profit + matched_commission + matched_swap
            trades.append(
                {
                    "number": len(trades) + 1,
                    "ea": label,
                    "symbol": symbol,
                    "side": "Long" if entry["type"] == "buy" else "Short",
                    "volume": round(matched, 4),
                    "open_time": entry["time"],
                    "close_time": timestamp,
                    "open_price": float(entry["price"]),
                    "close_price": price,
                    "gross_profit": round(matched_gross_profit, 2),
                    "commission": round(matched_commission, 2),
                    "swap": round(matched_swap, 2),
                    "total_costs": round(matched_commission + matched_swap, 2),
                    "net_profit": round(net, 2),
                    "result": "Win" if net > 0 else "Loss" if net < 0 else "Flat",
                    "source": "Native MT5 deals",
                    "entry_comment": entry["comment"],
                    "exit_comment": cells[12],
                }
            )
            entry["remaining"] = float(entry["remaining"]) - matched
            remaining_exit -= matched
            if float(entry["remaining"]) <= 1e-9:
                queue.pop(0)
    return trades

def _report_inputs(path: Path) -> dict[str, str]:
    text = _read_report(path)
    marker = text.lower().find("inputs:")
    if marker < 0:
        return {}
    end = text.lower().find("company:", marker)
    section = text[marker:end if end > marker else len(text)]
    values: dict[str, str] = {}
    for raw in re.findall(r"<b>(Inp[^<]+)</b>", section, flags=re.I | re.S):
        cleaned = _clean(raw).replace("\r", "").replace("\n", "")
        if "=" not in cleaned:
            continue
        name, value = cleaned.split("=", 1)
        values[name.strip()] = value.strip()
    return values

def _same_setting(expected: str, actual: str) -> bool:
    if expected.strip().lower() in {"true", "false"} or actual.strip().lower() in {"true", "false"}:
        return expected.strip().lower() == actual.strip().lower()
    try:
        return abs(float(expected) - float(actual)) < 1e-9
    except ValueError:
        return expected.strip() == actual.strip()

def parse_case(out):
    run=json.loads((out/'run.json').read_text());case=run['params']['InpCase'];report=out/(case+'.htm')
    inputs=_report_inputs(report)
    for key,value in run['params'].items():assert key in inputs and _same_setting(str(value),inputs[key]),(key,value,inputs.get(key))
    text=_read_report(report);stats=_native_metrics(report);trades=_native_trades(report,case)
    assert stats['initial_balance']==10000 and len(trades)==stats['trades']
    assert abs(sum(t['net_profit'] for t in trades)-stats['net_profit'])<.06
    audit=list(csv.DictReader((out/'audit.csv').open(encoding='utf-8-sig')))
    entry_audit=[a for a in audit if a['kind']=='entry'];assert len(entry_audit)==len(trades)
    journal=(out/'journal.txt').read_text()
    match=re.search(r'ONVP_SUMMARY\|'+re.escape(case)+r'\|([^\r\n]+)',journal);assert match,'Missing native audit'
    counters={k:float(v) for k,v in (p.split('=',1) for p in match[1].split('|'))}
    assert int(counters['entries'])==len(trades)
    assert counters['signals']==counters['entries']+counters['invalid_geometry']+counters['rejected']
    contract=run['contracts'][run['asset']]['trade_contract_size']
    balance=10000;seen=set();months=defaultdict(list)
    for t,a in zip(trades,entry_audit):
        opened=datetime.fromisoformat(t['open_time']).replace(tzinfo=timezone.utc);closed=datetime.fromisoformat(t['close_time']).replace(tzinfo=timezone.utc)
        day=opened.astimezone(NY).date();assert day not in seen,'More than one entry in a NY day';seen.add(day)
        assert opened.astimezone(NY).hour*60+opened.astimezone(NY).minute>=575,'Early entry'
        sign=1 if t['side']=='Long' else -1
        assert abs((t['close_price']-t['open_price'])*sign*t['volume']*contract-t['gross_profit'])<.12,'Contract P/L mismatch'
        stop=float(a['stop']);target=float(a['target']);risk=abs(t['open_price']-stop)*t['volume']*contract
        t.update(stop=stop,target=target,initial_risk_usd=risk,initial_risk_pct=100*risk/balance,
                 initial_rr=abs(target-t['open_price'])/abs(t['open_price']-stop),net_r=t['net_profit']/risk,
                 held_overnight=day!=closed.astimezone(NY).date(),
                 scheduled_exit_utc=datetime.fromtimestamp(int(a['cutoff_epoch']),timezone.utc).isoformat(),
                 exit_delay_minutes=max(0,(closed.timestamp()-int(a['cutoff_epoch']))/60),
                 entry_slippage_price=(t['open_price']-float(a['requested_entry']))*sign)
        t['open_time']=opened.isoformat();t['close_time']=closed.isoformat();balance+=t['net_profit'];t['balance_after']=round(balance,2)
        months[closed.astimezone(NY).strftime('%Y-%m')].append(t)
    pos=sum(max(0,t['net_profit']) for t in trades);neg=sum(max(0,-t['net_profit']) for t in trades)
    dd=re.match(r'([\d.]+)%',_metric(text,'Equity Drawdown Relative'));assert dd
    bdd=re.match(r'([\d.]+)%',_metric(text,'Balance Drawdown Relative'));assert bdd
    stats.update(asset=run['asset'],symbol=run['symbols'][run['asset']],mode=run['mode'],fingerprint=run['fingerprint'],
                 profit_factor=pos/neg if neg else None,win_rate_pct=100*sum(t['net_profit']>0 for t in trades)/len(trades) if trades else 0,
                 native_relative_equity_dd_pct=float(dd[1]),tick_observed_equity_dd_pct=counters['max_equity_dd'],
                 max_drawdown_pct=max(float(dd[1]),counters['max_equity_dd']),balance_drawdown_pct=float(bdd[1]),commission=sum(t['commission'] for t in trades),swap=sum(t['swap'] for t in trades),
                 average_rr=float(np.mean([t['initial_rr'] for t in trades])) if trades else None,
                 min_equity=counters['min_equity'],overnight_holdings=sum(t['held_overnight'] for t in trades),audit=counters,
                 exits_over_one_minute_late=sum(t['exit_delay_minutes']>1 for t in trades),
                 max_exit_delay_minutes=max((t['exit_delay_minutes'] for t in trades),default=0),
                 max_initial_risk_pct=max((t['initial_risk_pct'] for t in trades),default=0),report_sha256=sha(report),
                 warnings=[line.strip() for line in journal.splitlines() if any(s in line.lower() for s in ['real ticks absent','no real ticks','ticks discarded','mismatch','not enough money','no history data'])])
    for name,sign in [('win',1),('loss',-1)]:
        current=maximum=0
        for t in trades:
            current=current+1 if sign*t['net_profit']>0 else 0;maximum=max(maximum,current)
        stats['max_'+name+'_streak']=maximum
    stats['average_trade_usd']=stats['net_profit']/len(trades) if trades else 0
    stats['wins']=sum(t['net_profit']>0 for t in trades)
    stats['losses']=sum(t['net_profit']<0 for t in trades)
    stats['long_trades']=sum(t['side']=='Long' for t in trades)
    stats['short_trades']=sum(t['side']=='Short' for t in trades)
    stats['observed_roundtrip_commission_per_lot']=float(np.median([-t['commission']/t['volume'] for t in trades])) if trades else None
    stats['real_tick_start_lines']=sorted(set(line.split('Ticks',1)[-1].strip() for line in journal.splitlines() if 'real ticks begin from' in line))
    stats['months']=[dict(month=m,trades=len(ts),wins=sum(t['net_profit']>0 for t in ts),net_profit=round(sum(t['net_profit'] for t in ts),2),commission=round(sum(t['commission'] for t in ts),2),swap=round(sum(t['swap'] for t in ts),2)) for m,ts in sorted(months.items())]
    save(out/'trades.json',trades);return stats
