"""Readable report and scientific balance comparison from saved verified results."""
from pathlib import Path
import json,math,statistics
from datetime import datetime
from collections import defaultdict
ROOT=Path(__file__).resolve().parent
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def num(v,d=2):return '—' if v is None else f'{v:,.{d}f}'
def cash(v):return '—' if v is None else f'${v:,.2f}'
def date(v):return v[:10] if v else 'Not reached'
def table(lines,headers,rows):
 lines+=['','| '+' | '.join(headers)+' |','|'+'|'.join('---' for h in headers)+'|']
 lines+=['| '+' | '.join(str(v) for v in row)+' |' for row in rows];lines+=['']
def main():
 data=read(ROOT/'RESULTS.json');audit=read(ROOT/'DATA_AUDIT.json');frozen=read(ROOT/'FROZEN.json');verification=read(ROOT/'FINAL_VERIFICATION.json')
 labels={e['slug']:e['label'] for e in frozen['entries']};cases=data['cases'];assert len(cases)==8
 lines=['# FTMO $10K Swing — your fourteen EAs together','',
 'Completed research comparison, September 27, 2026. No live trades, account changes, production settings, BATs, website edits or Git pushes.', '',
 '## What these results mean','',
 '**These are conditional fitted-history scenarios, not reliable real-world pass probabilities.** Fresh native Exness MT5 signal histories are repriced and admitted into ONE shared $10,000 account. They are not native FTMO execution tests. Historical equity is not available tick by tick: open trades are marked using full-stop loss reserves. “Reserve failure” means that approximation crossed a limit; it does not establish an actual historical FTMO breach.', '',
 'All fourteen requested EAs are enabled in each case. Ordinary trades use fixed $50 or $70 planned stop risk (0.5%/0.7% of INITIAL capital); Gold News uses $30 per side, both pending sides retained. Strict lot rounding down; no adaptive multiplier, martingale, new entry logic or optimization. This is a research overlay, not the current production risk policy.', '',
 'Gold news has a $2 stop distance, so planned sizing is 0.15 lot per side, not 0.02. Its assumed 0.01 minimum lot fits the cap; the fallback is therefore not invoked. Slippage can increase actual fill-to-stop risk above $30. Commission, swaps and stop gaps can add further losses.', '',
 f"The largest news fill-to-original-stop exposure in the source ledger, resized to 0.15 lot, was {cash(verification['news_max_fill_to_original_stop_risk_at_015_lot'])} on {verification['news_worst_fill_open'][:10]}. This is NOT a realized loss and NOT a guaranteed maximum. The simulation uses the larger actual fill exposure for its news stop reserve. At gold $4,000, reserving both 0.15-lot orders at 1:15 consumes about $8,000 margin before other positions. Therefore a $30 news risk target does not mean every event can be admitted.", '',
 'Period: 2025-09-27 through 2026-09-27 exclusive. Native Model 4, 150 ms simulated delay. All native reports and initial order stops are audited. Tick-coverage quality is shown below; missing real history is generated by MT5.', '',
 'Two management cases: **margin-only** = no added portfolio gates, still shared modeled margin and hard-rule checks; **guarded** = $300 daily reserved-loss budget, $225 simultaneous initial risk, $150 per symbol/correlated metals, projected equity above $9,200, seven entries/day, stop new entries after three net losses, at most 80% reserved margin. Both news pending sides consume resources. These gates reject signals; they are not guaranteed loss caps and do not liquidate existing trades.', '',
 'Current FTMO public instrument API confirms XAU and US100 Swing leverage 1:15; USDJPY 1:30. Both news sides are reserved with no hedge-margin relief. Lot step/minimum 0.01 remains a platform-specification assumption. Native spread/gap prices and swaps are reused, not historical FTMO quotes. Commission floors and adverse execution/carry sensitivities are in PROTOCOL.md.', '',
 'FTMO model: +$1,000 Challenge then +$500 Verification, four opening days per phase, flat at passage; Prague midnight balance minus $500 daily equity floor; $9,000 static total equity floor. No 2-Step Best Day Rule and no evaluation expiry. Two business days between phases and five to funded activation are assumptions. First reward requested when flat, at least fourteen calendar days after first funded entry, with $25+ closed profit; 80% share; assumed receipt four business days later. Simulation stops at first request. Actual approval, payment and longer funded-account survival are not modeled.', '',
 '## Completion scenarios — stressed execution','',
 '1,000 matched joint-week paths per case. Source: 51 complete weeks, September 29, 2025–September 20, 2026; year-end partial blocks are excluded from bootstrap but retained in the historical replay. Preserve within-week cross-EA relationships; multi-week dependence, long-hold overlaps, holidays and session-clock transfers are imperfect. The 2/4/6-month labels below mean 60/120/180 calendar days. Same paths compare all risk/management/cost cases.', '',
 f"There are {verification['long_holds_over_seven_days']} source trades held longer than one week; the longest is {verification['longest_hold_days']:.1f} days. Resampling weekly blocks cannot preserve the full multi-week dependence of these positions. These scenarios do not replace a longer-block or forward validation."]
 rows=[]
 for r in cases:
  if not r['stress']:continue
  for h in r['summary']['horizons']:
   if h['days']==30:continue
   rows.append([f"{r['risk']/100:.1f}%",'Guarded' if r['guards'] else 'Margin-only',h['days'],f"{h['phase1_pass_pct']:.1f}%",f"{h['both_pass_pct']:.1f}%",f"{h['funded_pct']:.1f}%",f"{h['request_eligible_pct']:.1f}%",f"{h['payout_pct']:.1f}%",f"{h['breach_before_first_reward_pct']:.1f}%",f"{h['unfinished_evaluation_pct']:.1f}%"])
 table(lines,['Risk','Management','Days','Phase 1','Both passed','Funded active','Reward eligible','Assumed paid','Reserve failure','Still evaluating'],rows)
 lines+=['Milestone percentages overlap and must not be summed. Reserve failures, unfinished evaluations, administrative waits and first-reward states are separately reconciled in RESULTS.json. One minus pass probability is NOT blow-up probability. Zero simulated reserve failures is NOT zero live risk.','',
 'News parameters were fitted to this same year; other EAs and the DI filter were also previously selected on overlapping history. Repeating these observations 1,000 times does not produce independent evidence or remove overfitting. Execution failures and contractual disqualification are not assigned probabilities.','',
 '## Timing conditional on completion by day 180 — stress']
 rows=[]
 for r in cases:
  if not r['stress']:continue
  for key,label in [('phase1_days_among_phase1_passers','Phase 1 from start'),('phase2_days_from_availability_among_phase2_passers','Phase 2 from availability'),('funded_days_from_purchase','Funded from start'),('payout_days_from_purchase','Assumed first receipt from start')]:
   t=r['summary']['timing'][key];rows.append([f"{r['risk']/100:.1f}%",'Guarded' if r['guards'] else 'Margin-only',label,t['n'],num(t['median'],1),num(t['p10'],1)+'–'+num(t['p90'],1)])
 table(lines,['Risk','Management','Milestone','Completed / 1000','Median days','10th–90th days'],rows)
 lines+=['Different milestones have different completion cohorts; do not add medians. Unfinished paths are censored, not assigned zero or infinite time.','',
 '## Historical shared account — no phase resets or withdrawals','',
 'These returns are hypothetical trading balance changes, NOT withdrawable income. Replay stops if the reserve model flags a hard limit. Rows that stop early are not full-year invested returns; duration and open-position costs are disclosed.']
 rows=[]
 for r in cases:
  h=r['historical_continuous'];d=r['historical_details'];rows.append([f"{r['risk']/100:.1f}%",'Guarded' if r['guards'] else 'Margin-only','Stress' if r['stress'] else 'Reference',h['trades'],num(d['trades_per_month'],1),num(d['trades_per_weekday']),cash(h['balance']-10000),f"{(h['balance']-10000)/100:.2f}%",num(h['win_rate'])+'%',num(h['pf']),num(h['closed_dd_pct'])+'%',num(h['model_dd_pct'])+'%',str(h['max_win_streak'])+'/'+str(h['max_loss_streak']),date(h['breach_at']) if h['breach'] else 'No reserve failure'])
 table(lines,['Risk','Management','Costs','Trades','/month','/weekday','Net balance USD','Return','Win','PF','Balance DD','Reserve DD proxy','Max W/L','Stop date'],rows)
 lines+=['Frequency divides by the entire requested year (260 weekdays, holidays included), even if an account stops early. Reserve DD is not native measured equity DD or FTMO static initial-balance drawdown. Historical attribution is closed-trade P&L; any entry costs on open trades at a reserve stop are reported separately.','',
 '## Monthly USD breakdown — stressed guarded accounts']
 guards=[next(r for r in cases if r['risk']==risk and r['guards'] and r['stress']) for risk in (50.,70.)]
 months=sorted(set(m for r in guards for m in r['historical_details']['months']))
 table(lines,['UTC exit month','0.5% trades','0.5% net USD','0.7% trades','0.7% net USD'],[[m]+[v for r in guards for v in [r['historical_details']['months'].get(m,{}).get('trades',0),cash(r['historical_details']['months'].get(m,{}).get('net',0))]] for m in months])
 lines+=['September 2025 and September 2026 are partial months. These are continuous-account profits, not monthly payouts.','', '## Per-EA contribution — stressed guarded accounts']
 rows=[]
 for key,label in labels.items():
  row=[label]
  for r in guards:
   v=r['historical_details']['by_ea'].get(key,{})
   row += [v.get('trades',0),cash(v.get('net',0)),num(v.get('win_rate'))+'%',num(v.get('pf')),f"{v.get('max_win_streak',0)}/{v.get('max_loss_streak',0)}"]
  rows.append(row)
 table(lines,['EA','0.5% N','0.5% USD','0.5% Win','0.5% PF','0.5% W/L','0.7% N','0.7% USD','0.7% Win','0.7% PF','0.7% W/L'],rows)
 lines+=['Enabled is not the same as admitted: shared margin, simultaneous risk, minimum-lot sizing and daily rules can exclude signals. No EA is silently removed.','', '## Why signals were skipped — stress']
 rows=[]
 for r in cases:
  if not r['stress']:continue
  h=r['historical_continuous'];cc=h['counts'];rows.append([f"{r['risk']/100:.1f}%",'Guarded' if r['guards'] else 'Margin-only',cc.get('news_baskets',0),cc.get('news_margin_rejected',0),cc.get('margin_rejected',0),cc.get('min_lot_over_budget',0),cc.get('open_risk_rejected',0),cc.get('correlated_risk_rejected',0),cc.get('daily_budget_rejected',0),cc.get('total_loss_buffer_rejected',0),h['open_positions'],cash(h['unclosed_entry_costs'])])
 table(lines,['Risk','Management','News events admitted','News margin rejects','Other margin rejects','Min-lot rejects','Open-risk rejects','Correlated rejects','Daily-budget rejects','Total-buffer rejects','Open at stop/end','Unclosed entry fees'],rows)
 lines+=['News fill counts differ from event counts because either or both sides can fill, or neither may fill. Complete rejection categories are in RESULTS.json.','', '## One historical challenge starting September 27, 2025 — stress']
 rows=[]
 for r in cases:
  if not r['stress']:continue
  h=r['historical_challenge'];p={v['phase']:v['time'] for v in h['passes']}
  rows.append([f"{r['risk']/100:.1f}%",'Guarded' if r['guards'] else 'Margin-only',date(p.get(1)),date(p.get(2)),date(h['funded_at']),date(h['request_at']),date(h['receipt_at']),cash(h['reward']) if h['payout'] else 'Not received',date(h['breach_at']) if h['breach'] else 'No reserve failure'])
 table(lines,['Risk','Management','Phase 1','Phase 2','Funded','Reward request','Assumed receipt','Profit reward','Reserve failure'],rows)
 lines+=['Reward excludes fee refund, evaluation fee, tax, FX conversion, VPS and transaction charges. Earlier phase completion changes which trades occur during funded trading, so larger risk need not mean larger first reward.','', '## Most recent actual 2-, 4- and 6-month starts — stress']
 rows=[]
 for r in cases:
  if not r['stress']:continue
  for recent in r['recent_historical']:
   h=recent['result'];rows.append([f"{r['risk']/100:.1f}%",'Guarded' if r['guards'] else 'Margin-only',recent['months'],date(recent['start']),len(h['passes']),date(h['funded_at']),date(h['receipt_at']),cash(h['reward']) if h['payout'] else 'Not received',date(h['breach_at']) if h['breach'] else 'No reserve failure'])
 table(lines,['Risk','Management','Months','Start','Phases passed','Funded','Assumed paid','Profit reward','Reserve failure'],rows)
 lines+=['These are three overlapping historical paths, not three independent probability estimates. Source entries/exits come from the common-year runs; fresh restart-dependent EA state is not regenerated at each shorter window.','', '## Cost sensitivity and payout cash — all cases']
 rows=[]
 for r in cases:
  h=r['summary']['horizons'][-1];ci=h['payout_mc_only_interval'];rows.append([f"{r['risk']/100:.1f}%",'Guarded' if r['guards'] else 'Margin-only','Stress' if r['stress'] else 'Reference',num(h['funded_pct'],1)+'%',num(h['payout_pct'],1)+'%',num(h['breach_before_first_reward_pct'],1)+'%',cash(h['mean_first_reward_per_purchase']),cash(h['median_first_reward_if_paid']),f'{ci[0]:.1f}–{ci[1]:.1f}%'])
 table(lines,['Risk','Management','Costs','Funded 180d','Assumed paid 180d','Reserve failures','Mean first reward per attempt','Median reward if paid','MC-only payout interval'],rows)
 lines+=['Mean includes zero for paths without receipt by day 180. Intervals measure finite Monte Carlo draws only—not uncertainty from selection, limited history, execution, model assumptions or compliance. These are gross profit shares, not fee-adjusted cash returns.','', '## Fresh standalone native evidence — not portfolio returns']
 rows=[]
 prepared=read(ROOT/'prepared.json')
 for a in audit['eas']:
  m=a['native_metrics'];xs=sorted(prepared['rows'][a['ea']],key=lambda x:x['cl']);ws=ls=mw=ml=0
  for x in xs:
   ws=ws+1 if x['net_profit']>0 else 0;ls=ls+1 if x['net_profit']<0 else 0;mw=max(mw,ws);ml=max(ml,ls)
  win=sum(x['net_profit']>0 for x in xs)/len(xs)*100 if xs else 0
  rows.append([labels[a['ea']],len(xs),num(len(xs)/12,1),num(len(xs)/260),num(m['return_pct'])+'%',num(win)+'%',num(m['profit_factor']),num(m['max_drawdown_pct'])+'%',f'{mw}/{ml}',m['history_quality']])
 table(lines,['EA','Trades','/month','/weekday','Native return','Net win','Native PF','Reported native DD','Net max W/L','Coverage'],rows)
 lines+=['Standalone entries use current presets and their original native sizing, not the $50/$70/$30 overlay. Do NOT sum returns. Native reported DD may differ from floating-equity relative DD; the portfolio reserve proxy is separately labeled.','', '## Decision limits','',
 '- No automatic deployment: this is a study, not a verified live passing plan.',
 '- FTMO Swing news permission does not confirm approval of this particular pre-release two-sided straddle. Gap-trading and cumulative-risk restrictions still apply. Obtain written eligibility clarification.',
 '- Joint FTMO bid/ask equity, historical spreads/swaps, lot minima, rejection/fill behavior, server request counts and forward results remain to be verified. Model-implied payout is not promised payment.',
 '- Do not interpret a high win rate as safety: payoff size, shared exposure and adverse execution determine account survival.', '',
 '## Sources and reproducibility','',
 '[FTMO objectives](https://ftmo.com/en/trading-objectives/) · [Swing specifications](https://ftmo.com/en/faq/what-are-the-account-specifications/) · [Public instruments](https://ftmo.com/en/symbols/) · [Reward rules](https://ftmo.com/en/faq/how-do-i-withdraw-my-profits/) · [Forbidden practices](https://ftmo.com/en/forbidden-trading-practices/)', '',
 'PROTOCOL.md freezes assumptions; FROZEN.json freezes fourteen builds/settings; DATA_AUDIT.json reconciles each native report; FTMO_PUBLIC_SPECS.json records current official instrument data; SIMULATION_FROZEN.json hashes sources; RESULTS.json preserves all 8,000 paths, admission counts and ledgers; CHECKS.json records validations. FINAL_VERIFICATION.json independently checks all 8,000 path records, 32 horizon classifications, ten source/dependency hashes, eight cash ledgers and exact reruns of both stressed guarded histories.']
 (ROOT/'REPORT.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
 import matplotlib
 matplotlib.use('Agg')
 import matplotlib.pyplot as plt
 import matplotlib.dates as mdates
 fig,axes=plt.subplots(2,1,figsize=(12,9),sharex=True,sharey=True,layout='constrained')
 for ax,guard in zip(axes,[False,True]):
  for risk,color in [(50.,'#2563eb'),(70.,'#be4b11')]:
   r=next(r for r in cases if r['risk']==risk and r['guards']==guard and r['stress']);h=r['historical_continuous']
   ts=[datetime.fromisoformat(data['frozen']['source_start'])]+[datetime.fromisoformat(x['close']) for x in h['log']]
   ys=[10000]+[x['balance'] for x in h['log']]
   if h['breach']:
    ts.append(datetime.fromisoformat(h['breach_at']));ys.append(h['balance'])
   ax.step(ts,ys,where='post',label=f'{risk/100:.1f}% ordinary risk',color=color,linewidth=1.6,linestyle='-' if risk==50 else '--')
   if h['breach']:
    ax.plot(ts[-1],ys[-1],marker='x',color=color,markersize=8)
    ax.annotate('Reserve flag: '+h['breach_at'][:10],(ts[-1],ys[-1]),xytext=(8,-30),textcoords='offset points',fontsize=10)
  ax.axhline(10000,color='#777777',linewidth=.8);ax.set_ylabel('Balance at closures / stop (USD)');ax.grid(alpha=.18)
  ax.set_title('Guarded portfolio' if guard else 'Margin-only portfolio',loc='left');ax.legend(loc='upper left')
 axes[-1].xaxis.set_major_locator(mdates.MonthLocator(interval=2));axes[-1].xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'));axes[-1].set_xlabel('UTC date')
 fig.suptitle('Fourteen EAs together • $10,000 • stressed costs\nGold News: $30 per side; x marks reserve-model stop',fontsize=14)
 fig.savefig(ROOT/'balance_comparison.png',dpi=140);plt.close(fig)
 print('REPORT and balance comparison saved',flush=True)
if __name__=='__main__':main()
