# Generated by Django 5.2.17 on 2026-08-10 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.CharField(max_length=240)),
                ("description", models.TextField()),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("mt5_ea", "MT5 Expert Advisor"),
                            ("mt5_indicator", "MT5 Indicator"),
                            ("pine_strategy", "Pine Strategy"),
                            ("pine_indicator", "Pine Indicator"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In review"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("current_version", models.CharField(default="1.0.0", max_length=32)),
                ("symbol", models.CharField(blank=True, max_length=32)),
                ("timeframe", models.CharField(blank=True, max_length=16)),
                ("strategy_type", models.CharField(blank=True, max_length=80)),
                ("source_included", models.BooleanField(default=True)),
                ("support_days", models.PositiveSmallIntegerField(default=30)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification",
                    models.CharField(
                        choices=[
                            ("seller_reported", "Seller-reported"),
                            ("platform_parsed", "Platform-parsed report"),
                            ("platform_backtested", "Platform-backtested"),
                            ("independent", "Independently verified"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("initial_deposit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("leverage", models.CharField(default="1:100", max_length=20)),
                ("modelling", models.CharField(max_length=120)),
                ("commission_included", models.BooleanField(default=True)),
                ("profit_factor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("win_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                ("max_drawdown", models.DecimalField(decimal_places=2, max_digits=6)),
                ("total_trades", models.PositiveIntegerField()),
                ("net_return", models.DecimalField(decimal_places=2, max_digits=8)),
                ("equity_points", models.JSONField(blank=True, default=list)),
                ("drawdown_points", models.JSONField(blank=True, default=list)),
                ("report_checksum", models.CharField(blank=True, max_length=64)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_run",
                        to="marketplace.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-end_date",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "artifact_type", "price"], name="marketplace_status_d520df_idx"
            ),
        ),
    ]
