"""Build the human-readable research result from saved, audited evidence."""
from pathlib import Path
import json,math,re
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parent
def read(n):return json.loads((ROOT/n).read_text())
def link(n,label=None):return f'[{label or n}](<{(ROOT/n).as_posix()}>)'
def fmt(v,n=2):return '—' if v is None else f'{v:,.{n}f}'
def table(head,rows):return '\n'+' | '.join(head)+'\n'+' | '.join(['---']*len(head))+'\n'+'\n'.join(' | '.join(str(x) for x in row) for row in rows)+'\n'
def perf(st):return [st['trades'],fmt(st['trades_month']),fmt(st['trades_weekday']),fmt(st['return_pct'])+'%',fmt(st['pf']),fmt(st['win_rate'],1)+'%',fmt(st['equity_dd_pct'])+'%',f"{st['max_win_streak']}/{st['max_loss_streak']}"]
HEAD=['Model','Trades','/month','/weekday','Return','PF','Win %','Equity DD','W/L streak']
def prop_perf(h,capital,days):
    st=h['snapshot'];n=int(st['trades']);neg=st['negative']
    return [n,fmt(n/(days/30.4375)),fmt(n/(days*5/7)),fmt((st['balance']/capital-1)*100)+'%',fmt(st['positive']/neg if neg else None),
        fmt(100*st['wins']/n if n else None,1)+'%',fmt(st['envelope_dd_pct'])+'%',f"{int(st['max_win_streak'])}/{int(st['max_loss_streak'])}"]
def main():
    raw=read('RAW_RESULTS.json');over=read('OVERLAYS.json');native=read('NATIVE_PROP.json');diag=read('DIAGNOSTICS.json');audit=read('VERIFICATION.json');boot=read('BOOTSTRAP-FTMO.json');cfg=read('run-config.json')
    out=['# Bruni statistical models — FTMO / FundedNext research\n',
    '28 September 2026 · Research only · **No live changes**\n',
    '## Decision\n',
    '**Do not advance this batch to optimization or deployment.** The M15 entry approximations fail the frozen three-year gate. The risk overlays do not demonstrate a reliable improvement over fixed risk. This is a rejection of these explicit implementations on these data—not proof that Bruni’s undisclosed system cannot work.\n',
    '- Nasdaq triple-print: last year +5.44%, PF 1.20, but latest six months −1.17%, and three-year screen PF 1.04. The wick filter does not fix it.\n- USDJPY: neither triple-print candidate passes the three-year screen; both lose over the latest year and six months.\n- Existing portfolio: 972 native opportunities across 13 EAs. No statistically convincing win/loss clustering after multiplicity adjustment; only 222 opportunities have enough prior data for our conditional-Kelly estimate.\n- The evidence-gated seven-loss boost never activates: the largest available historical state sample is 7, against the required 30. “Another win is due” is not a substitute.\n- No tested risk overlay clears the predeclared paired-return confidence gate. Some reduce drawdown; that is not evidence for the video’s extreme risk increases.\n',
    '## What was built, and what was not\n',
    'Built a tester-only M15 EA with actual/peripheral zone approximations, triple-print validation, a wick-gap filter, a simpler one-print control, 2R target, fixed price-risk and a 48-hour/Friday time exit. Tested Nasdaq CFD (USTEC) and USDJPY; no metals. **The entry trigger, pivot definition, zone segmentation and index wick threshold are ours.** The transcript does not specify enough to reproduce the speaker’s exact system. The full frozen definitions are in '+link('RULES.md')+'.\n',
    'Separately built six offline sizing policies: fixed, half risk after a loss, capped conditional quarter-Kelly, GARCH volatility cap, combined cap, and evidence-gated VAM. These use earlier closed trades of the same EA only. Unexecuted original opportunities remain a virtual “shadow” ledger, which a live implementation would also need to maintain. Maximum standalone increase is 1.25×; no 0.5%→3% jump.\n',
    'Not implemented as a claimed trading edge: the missing exact Asia-session entry schematics; volume-profile hierarchy; a fitted Hamilton Markov-switching model; GARCH calm-regime direction reversal; a new target optimization; or automatic rotation/replacement of prop accounts. The supplied material does not establish their parameters or efficacy. Reversal needs its own opposite-order execution test, not negating existing P&L. There is no stage-5 parameter search because the raw gate failed.\n',
    '## Native M15 results\n',
    'All variants were frozen before tests. Each starts with $10,000 and targets $100 initial price-risk per position, before commission/slippage; lots round down. This is not compounded 1% risk. Six-month/year tests use native Model 4 real-tick mode with 150 ms delay and source broker costs. Three/five-year results below are **Model 1 screens**, not real-tick confirmation. PF uses complete net trade cash, including costs. Equity DD here is the native report’s peak-relative equity drawdown. /weekday includes all weekdays in the window, including no-trade days. W/L means maximum consecutive winning/losing trades.\n']
    for window in ['6m','1y','3y','5y']:
        out.append(f'### {window} — '+('native real-tick mode' if window in ['6m','1y'] else 'fast historical screen')+'\n')
        rs=sorted([r for r in raw if r['window']==window],key=lambda r:(r['symbol'],r['variant']))
        out.append(table(HEAD,[[r['symbol']+' '+r['variant']+(' †' if r['stats']['capital_exhausted'] else '')]+perf(r['stats']) for r in rs]))
    out.append('† The five-year Nasdaq control exhausts its test capital and stops taking all later opportunities. Its −100.10% is a failed, capital-limited path—not a valid complete five-year opportunity benchmark. Do not use it to claim that the candidate’s five-year excess return is robust. Candidate rejection already follows from PF below 1.15 on the three-year screen. All four non-control candidates fail; none was sent for long-window Model 4 confirmation.\n')
    out.append('## Prop-account results for the new entry approximations\n')
    out.append('Replay uses the **one-year native trades**, rescaled through the conservative shared-equity account model. It does not reproduce target-server fills. Price paths use sampled native equity and conservative interval lows; low estimates retain some source fee/financing effects, so the envelope is deliberately conservative. Exness lot minima are USTEC0.05 and USDJPY0.01; target-firm symbol specifications still need verification.\n')
    out.append('FTMO: $10,000 Swing two-step, 0.50% maximum base price-risk. FundedNext: $5,000 Stellar Instant, 0.25% maximum base risk, further capped by remaining loss headroom. Firm rules and our tighter guards are described below. “Stress” is a hypothetical adverse-cost scenario, not measured FTMO/FundedNext slippage.\n')
    for firm,capital in [('FTMO',10000),('Instant',5000)]:
        out.append('### '+firm+' — full-year account replay, no withdrawals\n')
        out.append(table(HEAD,[[x['tag'].replace('-1y-m4','')+(' stress' if x['stress'] else ' base')]+prop_perf(x['historical'],capital,365) for x in native if x['firm']==firm]))
    out.append('These returns include risk/margin rejection of entries and profit-policy deductions, and are not the native EA returns above. No-withdrawal balances are not payouts. All these replay paths stayed inside the modeled breach barriers; risk guards can stop further trading before a formal breach. A low breach count is not proof of profitable or payout-ready trading.\n')
    out.append('### Payout lifecycle — new candidates\n')
    horizons=', '.join(f"{h['starts']} matured {h['days']}-day starts" for h in native[0]['rolling'])
    out.append('Weekly historical restarts yield '+horizons+'. These windows overlap heavily. Counts are **historical conditional eligibility frequencies, not forecast probabilities or independent trials**. Cash assumes approval and excludes acquisition, EA-addon, withdrawal and other paid fees.\n')
    # Counts are read dynamically below, rather than relying on the explanatory sentence.
    for x in native:
        if 'control' in x['tag']:continue
        h=x['rolling'][-1]
        out.append(f"- {x['tag'].replace('-1y-m4','')} / {x['firm']} / {'stress' if x['stress'] else 'base'}: at 180 days {h['payout']}/{h['starts']} starts reach an eligible payout; mean modeled cash ${h['mean_cash']:.2f}; {h['breach_before']+h['breach_after']} drawdown breaches; {h['compliance_blocked']} QuickStrike blocks.\n")
    out.append('For Nasdaq triple-print this is only about $33 mean cash over 180 days under the Instant base assumptions, falling to about $13 under stress, before paid fees. No new candidate reaches an FTMO payout in the tested 180-day restarts. This does not justify buying an account for these models.\n')
    out.append('## Risk overlays on the existing 13-EA portfolio\n')
    out.append('Common source: 27 September2025–25 September2026 (exclusive end). Validation replay: 27 March–25 September2026. Source EAs/settings were already selected using historical evidence, so this is **not an untouched out-of-sample test**. Multipliers themselves are causal: no trade’s result is usable until it closed strictly before the next entry minute. Broader price correlation and overlapping trades remain relevant even when binary outcome clustering is weak.\n')
    out.append('Below is second-half account replay without withdrawals. Same source prices, guards and fee policy for every overlay. DD is conservative peak-to-trough equity decline divided by initial capital, **not** the firms’ loss threshold or native peak-relative DD. A funded-style static FTMO loss barrier can survive a peak-to-trough DD larger than 10% of initial capital when earlier profits provide buffer. This should not be mistaken for passing evaluation phases.\n')
    for firm,capital in [('FTMO',10000),('Instant',5000)]:
        out.append('### '+firm+' — chronological validation\n')
        out.append(table(HEAD,[[x['model']+(' stress' if x['stress'] else ' base')]+prop_perf(x['historical']['validation'],capital,182) for x in over if x['firm']==firm]))
    out.append('FTMO half-risk-after-loss improves this guarded replay’s drawdown and return, but takes more trades because smaller orders pass margin/exposure guards. In the equal-opportunity shadow ledger it actually removes 15.17R of return. That distinction matters: it is not evidence of a dependable “next trade after a loss” advantage. Conditional Kelly’s apparent benefit is also not robust enough to promote.\n')
    out.append('### Rolling payout check for the existing portfolio\n')
    out.append('Second-half Monday starts mature into 22 30-day, 18 60-day and 9 120-day observations. There are **no matured 180-day starts** after30March in this data. FTMO has no payout within the tested120-day horizons for any policy, though some paths pass an earlier evaluation stage. Instant120-day results follow; cash is before fees and all provider discretion.\n')
    for x in over:
        if x['firm']!='Instant':continue
        h=next(v for v in x['rolling'] if v['days']==120)
        out.append(f"- {x['model']} ({'stress' if x['stress'] else 'base'}): {h['payout']}/{h['starts']} eligible; mean cash ${h['mean_cash']:.2f}; drawdown breaches {h['breach_before']+h['breach_after']}; compliance blocks {h['compliance_blocked']}.\n")
    out.append('### Statistical validation and the 10,000-path check\n')
    out.append('All 13 per-EA Fisher transition tests have raw p-values above0.16; Holm-adjusted p-values are1.00. This is insufficient evidence of serial win/loss predictability, not proof of exact independence. Samples range from11 to199 trades per EA, so combining them into “972 trades” cannot solve a per-strategy sample shortage. Conditional Kelly qualifies on222/972 opportunities; VAM qualifies onnone. Full estimates, Wilson intervals, chronological chunks, expectancy and profit factor with the best winner removed are in '+link('DIAGNOSTICS.json')+'.\n')
    out.append('The paired block bootstrap resamples 28-day blocks of the **realized second-half shadow-ledger differences**, 10,000 paths. It retains zero-trade days. The following are net-R differences versus fixed risk, with fifth/ninety-fifth percentile sampling bounds. This is a diagnostic distribution, **not** a new simulation of adaptively re-estimated Kelly/GARCH states on each synthetic path, and not a future prop pass probability.\n')
    for b in boot:out.append(f"- {b['model']}: observed {b['observed_net_r_difference']:+.2f}R; bootstrap range [{b['bootstrap_difference_p05']:+.2f}, {b['bootstrap_difference_p95']:+.2f}]R.\n")
    out.append('No non-control model has a positive lower bound. Risk reductions naturally can reduce both gains and drawdown; these difference tests do not by themselves rank utility or prove volatility sizing is useless. No full stage-6 promotion Monte Carlo was warranted after the earlier gates failed.\n')
    out.append('### GARCH findings and skill fallback\n')
    out.append('The regime-analysis skill influenced the past-data-only design and prefix-invariance tests. Its referenced Markov helper was absent locally. The study therefore directly implemented the interview’s GARCH(1,1) volatility forecast using constrained estimation, not an undisclosed substitute Markov classifier. GARCH forecasts conditional variance—not the next direction or a guaranteed calm session. [Model/forecast reference](https://arch.readthedocs.io/en/latest/univariate/forecasting.html).\n')
    out.append('The isolated collector supplied540–542 daily bars per instrument, starting1January2025, not the requested2021 history. This still supports the frozen252-return minimum; first forecasts start23–24October2025. Of972 opportunities,232 lack enough forecast history to assign a bucket and use the default sizing. Source daily bars include short Sunday sessions, so volatility buckets mix session lengths. All36 monthly fits converged, but calibration was imperfect: e.g. Nasdaq extreme-bucket predicted variance averages3.83 percentage-points-squared against2.37 realized. No tuning or reverse-direction rule was added after seeing this. See '+link('GARCH_AUDIT.json')+'.\n')
    out.append('## Drawdown shield: cash, exposure and account constraints\n')
    out.append('In the transcript’s simple noncompounded example (weekly−7%, +3%,−4%, +4%), four$50k accounts traded one at a time generate−$2,000 combined simulated trading P&L. Withdrawing the two winning slices gives$3,500 gross and$2,800 cash at an assumed80% split, leaving$194,500 combined simulated balance. Two accounts retain a combined$5,500 drawdown.\n')
    out.append('At the same percentage risk, one$200k account instead takes four times the active dollar exposure and loses$8,000. Reducing that single account’s percentage risk to one-quarter gives the same−$2,000 gross result as the rotation. Thus the comparison combines less dollar risk with segregated payout accounting; it does not create a market edge.\n')
    out.append('**Simulated balances are not trader-owned cash.** Adding residual account balances to payouts is not a valid measure of personal wealth. In this toy example actual trader cash is$2,800 minus all account/EA/reset/other paid fees; it is not automatically a$2,700 personal loss. Future earning capacity and probability of losing accounts still matter. The transcript’s80% split is not our Stellar Instant Tier1 assumption. We did not buy, cycle, sacrifice or replace accounts.\n')
    out.append('FTMO explicitly prohibits account rolling and substantially inconsistent position sizing. FundedNext also restricts account rolling; its example concerns acquiring multiple evaluations and deliberately sacrificing some. Ordinary ownership of multiple accounts is not automatically the same thing, but an operational “lose this account, move on” plan is not treated as approved. Small payouts do not excuse breaches. [FTMO practices](https://ftmo.com/en/forbidden-trading-practices/), [FundedNext practices](https://help.fundednext.com/en/articles/8020351-what-are-the-restricted-prohibited-trading-strategies).\n')
    out.append('## Rules and assumptions checked on28September2026\n')
    out.append('- FTMO **two-step**, not one-step:10% then5% targets, four entry days per phase,5% daily equity-loss amount resetting at Prague midnight and10% static overall loss amount. These differ from one-step rules on the same page. Our simulation uses two/five business days for review/handover and14-day funded payout timing; timing is an assumption, not a service guarantee. [Trading objectives](https://ftmo.com/en/trading-objectives/).\n')
    out.append('- Stellar Instant: no formal daily-loss limit;6% balance-trailing maximum loss, capped at initial balance, not reset down by withdrawals. We retain an additional3% initial-capital cushion when withdrawing. Our tighter0.75% internal daily stop is **ours**, not a FundedNext rule. [Loss-limit policy](https://help.fundednext.com/en/articles/11641163-what-are-the-daily-loss-limit-and-the-maximum-loss-limit-for-the-stellar-instant-accounts).\n')
    out.append('- Instant cash timing: at least1% growth after14days or5% growth confirmed at end-of-day. Tier1 cash split modeled70%; no scaling-tier uplift modeled. [Eligibility](https://help.fundednext.com/en/articles/11641693-what-is-the-eligibility-criteria-for-my-performance-reward-in-the-stellar-instant-account).\n')
    out.append('- Instant requires stops and ordinarily limits cumulative open risk to3%, or1% after reclassification. Its news attribution credits40% of positive flagged profit while retaining full losses; any execution within±5minutes can qualify. QuickStrike concerns profitable trades closed within30seconds reaching30% of recorded positive profit. [Clarity Cards](https://help.fundednext.com/en/articles/15644011-what-are-the-clarity-cards-and-how-do-they-affect-my-account).\n')
    out.append('- Official QuickStrike descriptions conflict: the Clarity page describes deduction/termination on a second violation; the general prohibited-strategies page describes termination at the breached cycle. The simulator conservatively blocks cash at the first qualifying request and records a **compliance block separately from drawdown breach**. This is not an assertion that the firm always terminates on the first violation. No modeled case here reached that block.\n')
    out.append('- Instant’s dedicated EA page requires its paid addon, customized/distinct strategies and compliance with its allocation/copying restrictions; it also restricts EAs integrated with third-party tools such as Telegram/WhatsApp. Any planned production adaptation needs a separate eligibility check. Leverage uses the stricter help-page value: indices5, gold7.5, forex30; marketing material may differ. These pages were accessible earlier in this session but later returned403 on recheck. [EA policy](https://help.fundednext.com/en/articles/11641338-can-i-use-ea-in-stellar-instant), [Leverage](https://help.fundednext.com/en/articles/11641369-what-is-the-leverage-provided-in-the-stellar-instant-accounts).\n')
    out.append('## Important corrections to the interview\n')
    out.append('1. Two wins out of six is33.33%, not23%. Comparing unconditional win rate with win rate after a loss gives a percentage-point difference, not an autocorrelation coefficient and not a90% next-win probability.\n2. The Lo–MacKinlay paper studied weekly historical stock returns. It does not validate serial predictability in these EA trades or show that seven losses imply an imminent win. [Author’s abstract](https://www.mit.edu/~alo/Papers/lo-mackinlay-88.html).\n3. Binary Kelly is f=p−(1−p)/b for fixed+ b/−1 payoffs. It maximizes a particular long-run log-growth objective under its assumptions; it does not enforce prop drawdown survival. Our real trades have variable payoffs, gaps and costs, so even fractional Kelly is an approximation.\n4. Zero serial outcome correlation does not rule out useful sizing based on volatility, expected payoff, spread, exposure or other independently validated predictors.\n5. Reversing a75%-losing strategy does not guarantee75% wins: both sides pay costs, their barriers can differ, fills and holding times change, and both directions can lose net.\n6. More trades reduce sampling error only under appropriate dependence assumptions. A thousand observations, stable chunks or a published paper do not prove a live edge. Target selection and repeated testing still create overfitting risk.\n7. Profit factor and expectancy both depend on the same underlying cash outcomes; removing the largest winner is a sensitivity check, not a universal edge certificate. Sharpe requires a specified return frequency and volatility denominator.\n')
    out.append('## Evidence limitations and audit\n')
    out.append('This study uses exactly 972 existing portfolio opportunities, not thousands of independent Bruni trades, with only 29 locally known news events in the source calendar. Target-firm bid/ask ticks, full news coverage, financing schedules, payout discretion, plan availability and actual paid fees remain unverified. CFDs are not NQ futures; index levels and contract values are not interchangeable. Source spread records contain zeros, so native costs alone can be optimistic.\n')
    out.append('Hypothetical stress reduces positive gross profits10%, worsens negative gross profits10%, adds spread/slippage allowances ($20/lot gold,$2/lot Nasdaq or0.02JPY converted per FX lot), and stresses carry. It is not a measured broker cost forecast. No paid-fee ROI or guarantee is reported. Equal percentage risk is not equal dollar risk across$10k and$5k accounts.\n')
    out.append(f"Checks: {audit['tests']} automated tests passed; {audit['native_cases']} native runs (6 smoke, 12 recent/year Model-4 runs, 12 long-window screens); {audit['native_trace_and_cash_checks']:,} native trace/cash items checked; maximum cash reconciliation error below $0.01. All six overlapping 6m/1y comparisons match trade-for-trade after the initial boundary week ({sum(x['six_month_trades'] for x in audit['nested_window_parity'])} matched trades).\n")
    out.append('Tests cover causality, same-minute/pending trade exclusion, per-EA training, GARCH prefix invariance, sizing caps, stop-loss breaches before profitable closes, FTMO phases, Prague daylight saving, Instant floor retention, minimum lots, QuickStrike block classification and fixed-policy parity with the prior simulator. Source hashes and frozen rules remain unchanged. The live MT5 process retained the same PID and creation time; no production tracked files changed.\n')
    out.append('## Artifacts and next decision\n')
    out.append('Research implementation: '+link('BruniProxy.mq5')+'; frozen configuration: '+link('run-config.json')+'; raw evidence: '+link('RAW_RESULTS.json')+'; account results: '+link('NATIVE_PROP.json')+' and '+link('OVERLAYS.json')+'; verification: '+link('VERIFICATION.json')+'. Full native reports, deal ledgers, settings, tick traces and journals are retained under the native folder. Reproduction commands are in '+link('README.md')+'.\n')
    out.append('**Next useful input is the exact video/chart entry examples or a complete mechanical rule sheet**, especially how an impulse/retracement becomes a valid breakout and the Asia-session entry trigger. That would permit a new frozen exact-specification test. It would not justify tuning this failed approximation on the same recent outcomes. No EA, risk policy or account-rotation plan is approved for deployment from this study.\n')
    text='\n'.join(out)
    coverage='**Tick-quality limitation:** both symbols have real ticks only from 1 January 2026. The 6-month tests report 100% real ticks; the 1-year runs report 63% real ticks over the full tester window including warm-up, with generated ticks earlier. November 2025 smoke tests use generated ticks (0% real). Thus one-year results and their prop replays are MIXED-tick evidence, not fully real-tick validation.\n\n'
    text=text.replace('### 6m — native real-tick mode',coverage+'### 6m — 100% real-tick report quality')
    text=text.replace('### 1y — native real-tick mode','### 1y — mixed real/generated ticks')
    # Natural spacing for transcript-style number runs in prose, without altering code or URLs.
    for a,b in [('September2025','September 2025'),('September2026','September 2026'),('March2026','March 2026'),('after30March','after 30 March'),('tested120-day','tested 120-day'),('Instant120-day','Instant 120-day')]:text=text.replace(a,b)
    pieces=re.split(r'(\[[^\]]*\]\([^\n]*?\))',text)
    for i in range(0,len(pieces),2):
        part=pieces[i]
        part=re.sub(r'\b([A-Za-z]{3,})(?=\d|\$)',r'\1 ',part)
        part=re.sub(r'(?<=\d)(?=(?:January|March|October|September|December|days|monthly|Monday|weekly|trades|observations|prior|opportunities|quotes|records|history|historical|percentage|instruments)\b)', ' ',part)
        part=re.sub(r'(?<=[%\d])(?=[A-Za-z]{3,}\b)', ' ',part)
        pieces[i]=part
    text=''.join(pieces)
    (ROOT/'REPORT.md').write_text(text,encoding='utf-8')
    print('REPORT written',len(text),'characters',flush=True)
if __name__=='__main__':main()
