// AUTO-GENERATED by Calyx news_pulse_calendar.py v1.0.
// Do not edit release timestamps by hand. Regenerate from the FXMacroData MCP.
#ifndef CALYX_NEWS_PULSE_TESTER_CALENDAR_MQH
#define CALYX_NEWS_PULSE_TESTER_CALENDAR_MQH

#define NP_TESTER_CALENDAR_COVERAGE_START_DATE 20260612
#define NP_TESTER_CALENDAR_COVERAGE_END_DATE 20260911
#define NP_TESTER_CALENDAR_EXPECTED_EVENTS 8

long NP_GENERATED_EVENT_UTC_EPOCHS[]={1781719200,1782995400,1784032200,1785348000,1786105800,1786537800,1788525000,1789129800};
string NP_GENERATED_EVENT_KINDS[]={"FOMC","NFP","CPI","FOMC","NFP","CPI","NFP","CPI"};

string NP_GeneratedCalendarProvider() { return "FXMacroData MCP"; }
string NP_GeneratedCalendarHash() { return "afc692c0d92ec324e27b8e636d56a36710c7ce3f356ad4aea96ce6bae9f3348c"; }
string NP_GeneratedCalendarFetchedAt() { return "2026-09-11T14:35:25.867069+00:00"; }
int NP_GeneratedCalendarEventCount() { return ArraySize(NP_GENERATED_EVENT_UTC_EPOCHS); }

#endif
