"""Static self-contained report, all hours retained, no live-data or trading API."""
from pathlib import Path
import html,json
R=Path(__file__).resolve().parent
def load(p):return json.loads((R/p).read_text())
def fmt(v,n=2,suffix=''):return 'N/A' if v is None else f'{v:,.{n}f}{suffix}'
def main():
 rows=load('NATIVE-SUMMARY.json');overnight=load('NATIVE-OVERNIGHT.json');candidates=load('CANDIDATES.json');audit=load('AUDIT.json');receipts=load('RECONCILIATION.json')
 assert len(rows)==288 and len(overnight)==2
 heads=['NY hold','CT hold','Side','Trades','Win rate','PF','Return','Closed DD','Daily Sharpe','Max wins','Max losses','Net $ / trade','95% mean CI ($)','Adjusted p','Excluded positions']
 def table(data):
  body=[]
  for r in data:
   cells=[f'{r["hour"]:02}:00–{(r["hour"]+1)%24:02}:00',f'{r["central_hour"]:02}:00–{r["hour"]:02}:00',r['side'].upper(),str(r['trades']),fmt(r['win_rate_pct'],1,'%'),fmt(r['pf']),fmt(r['return_pct'],2,'%'),fmt(r['closed_dd_pct'],2,'%'),fmt(r['sharpe_daily']),fmt(r['max_win_streak'],0),fmt(r['max_loss_streak'],0),fmt(r['mean_net_points']),('N/A' if r.get('ci95_low') is None else f'{r["ci95_low"]:.2f} to {r["ci95_high"]:.2f}'),fmt(r.get('p_adjusted_maxT'),3),str(r['excluded_positions'])]
   body.append('<tr>'+''.join('<td>'+html.escape(v)+'</td>' for v in cells)+'</tr>')
  return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+x+'</th>' for x in heads)+'</tr></thead><tbody>'+''.join(body)+'</tbody></table></div>'
 sections=[]
 for asset in ['US30','US100','SP500']:
  for window in ['1y','3m']:
   d=[r for r in rows if r['asset']==asset and r['window']==window]
   sections.append(f'<section data-asset="{asset}" data-window="{window}"><h2>{asset} — '+('One year' if window=='1y' else 'Three months')+'</h2><p>'+d[0]['start']+' through 2026-10-02 inclusive. '+html.escape(d[0]['history_quality'])+'.</p>'+table(d)+'</section>')
 shortlist=['<table><thead><tr><th>Asset / NY / side</th><th>Year: N / WR / PF / return / Sharpe / streak</th><th>3 months: N / WR / PF / return / Sharpe / streak</th></tr></thead><tbody>']
 for c in candidates:
  cells=[f'{c["asset"]} {c["hour"]:02}:00 {c["side"].upper()}']
  for w in ['1y','3m']:
   q=c[w];cells.append(f'{q["trades"]} / {q["win_rate_pct"]:.1f}% / {q["pf"]:.2f} / {q["return_pct"]:+.2f}% / {q["sharpe_daily"]:.2f} / {q["max_win_streak"]}')
  shortlist.append('<tr>'+''.join('<td>'+html.escape(v)+'</td>' for v in cells)+'</tr>')
 shortlist.append('</tbody></table>')
 otable='<table><thead><tr><th>Window</th><th>Trades</th><th>Win rate</th><th>PF</th><th>Return</th><th>Closed DD</th><th>Sharpe</th><th>Win / loss streak</th><th>Commission</th><th>Swap</th></tr></thead><tbody>'
 for q in overnight:otable+='<tr>'+''.join('<td>'+v+'</td>' for v in [q['window'],str(q['trades']),fmt(q['win_rate_pct'],1,'%'),fmt(q['pf']),fmt(q['return_pct'],2,'%'),fmt(q['closed_dd_pct'],2,'%'),fmt(q['sharpe_daily']),f'{q["max_win_streak"]} / {q["max_loss_streak"]}',fmt(q['commission']),fmt(q['swap'])])+'</tr>'
 otable+='</tbody></table>'
 positive_significant=[r for r in rows if r['trades'] and r['mean_net_points']>0 and r.get('p_adjusted_maxT',1)<.05]
 conclusion=f'{len(positive_significant)} positive hourly results pass the 5% family-adjusted zero-mean test. This is not a matched random-entry test and is not independent validation.'
 provenance='<table><thead><tr><th>Run</th><th>History</th><th>Executed</th><th>Kept</th><th>Excluded</th><th>Late exits</th><th>Missing M1</th><th>Report net $</th></tr></thead><tbody>'
 for q in receipts:provenance+='<tr>'+''.join('<td>'+html.escape(str(v))+'</td>' for v in [q['tag'],q['history_quality'],q['all_executed_positions'],q['kept_positions'],q['excluded_positions'],q['excluded_late_exit'],q['excluded_missing_m1'],fmt(q['native_report_net_cash'])])+'</tr>'
 provenance+='</tbody></table>'
 template='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>US indices hourly comparison</title><style>
:root{color-scheme:dark;--bg:#081612;--fg:#e6f5ed;--muted:#b0c8bc;--edge:#29483b;--panel:#0f221b;--mint:#7ff1c6}*{box-sizing:border-box}body{background:var(--bg);color:var(--fg);font:15px/1.6 system-ui,sans-serif;margin:0}main{max-width:1600px;margin:auto;padding:32px 24px}h1{font-size:36px;line-height:1.2;margin:6px 0 18px}h2{font-size:23px;margin-top:30px}p{color:var(--muted);max-width:1100px}a{color:var(--mint)}.notice{padding:16px 20px;border:1px solid #756d2a;border-radius:12px;background:#262818;margin:20px 0}.controls{display:flex;flex-wrap:wrap;gap:16px;padding:18px;background:var(--panel);border:1px solid var(--edge);border-radius:14px}label{display:grid;gap:6px}select{font:inherit;color:var(--fg);background:var(--bg);padding:10px 14px;border:1px solid var(--edge);border-radius:8px}button{font:inherit;background:var(--mint);color:#072015;border:0;border-radius:8px;padding:10px 16px;cursor:pointer;align-self:end}table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums;font-size:14px}th,td{padding:11px 12px;text-align:right;white-space:nowrap;border-bottom:1px solid var(--edge)}th{background:var(--panel);color:var(--muted);font-weight:500}th:first-child,td:first-child{text-align:left}tbody tr:hover{background:var(--panel)}.scroll{overflow-x:auto;border:1px solid var(--edge);border-radius:12px}section[hidden]{display:none}details{margin-top:28px}summary{cursor:pointer;color:var(--mint)}.label{letter-spacing:2px;color:var(--mint);font-size:13px}footer{margin-top:40px;color:var(--muted)}@media print{body{color:#000;background:#fff}.controls{display:none}section[hidden]{display:block}p{color:#333}th,td{white-space:normal;font-size:10px;padding:4px}.scroll{overflow:visible}}
</style></head><body><main><div class="label">CALYX · RESEARCH ONLY · 3 OCTOBER 2026</div><h1>US indices hourly comparison</h1><p>Exness US30, USTEC (US100) and US500 (SP500). Both buys and sells, every eligible hour. One year: 3 Oct 2025–2 Oct 2026. Three months: 3 Jul–2 Oct 2026. New York times use US daylight saving; US Central is one hour earlier.</p>
<div class="notice">Native MT5 comparison, fixed one CFD lot and an independent $10,000 reference per hour strategy. No stop-loss or take-profit. This is not 1%-risk sizing, a shared portfolio, a funded-account pass forecast or a margin-tested $10,000 account. These CFDs do not equal one ES or NQ contract.</div>
<div class="controls"><label>Asset<select id="asset"><option>US30</option><option selected>US100</option><option>SP500</option></select></label><label>Period<select id="window"><option value="1y">Last year</option><option value="3m">Last three months</option></select></label><button id="all">Show all six tables</button></div>
__TABLES__
<h2>Hours meeting both-window descriptive screens</h2><p>At least 30 trades per window, PF ≥1.20, win rate ≥52%, positive daily Sharpe in both. Sorted by the lower of the two Sharpes. These overlapping samples and retrospectively screened candidates are not untouched validation. We have not installed or selected a new EA.</p><div class="scroll">__CANDIDATES__</div><p>__CONCLUSION__</p>
<h2>Screenshot settings — SP500 overnight</h2><p>Buy 18:00 Central / 19:00 New York; exit 05:00 Central / 06:00 New York next day. Long enabled; short, SL and TP disabled. The screenshot’s $4,500 SL and $2,000 TP are therefore inactive. Below includes native charged costs. Exact original ES results cannot be reproduced with an Exness CFD contract.</p><div class="scroll">__OVERNIGHT__</div>
<details><summary>Execution, exclusions and statistics</summary><p>Native Model 4 with 150ms execution setting. Actual net deals include commission, fees and charged swap. Only complete minute intervals with entry/exit in the scheduled minutes count. Quoted bars are not always tradable: delayed closes and missing-minute intervals are excluded and shown separately. NY 16:00 and 17:00 were not entered due to the known daily closure. Sunday starts are excluded. Historical session restrictions in the MT5 test use the available broker contract schedule; this is a limitation of annual comparisons.</p><p>Daily Sharpe = mean daily realised P/L / daily standard deviation × √252, including zero-trade weekdays; it is not MT5’s built-in Sharpe. Drawdown is from closed balance only. Floating-equity drawdown for the post-exclusion sample is not available. Win rate uses net profit after costs; flat results break streaks. $1 per index point for each tested one-lot CFD, verified from broker tick specs. Fixed-lot returns across different index levels are not equal-risk comparisons.</p><p>Confidence intervals and adjusted p-values use 10,000 five-date moving-block bootstrap resamples. The two-sided max-T family includes all nonempty directions/hours/assets within each period. This tests zero mean, not a matched random-entry strategy. Recent three months overlap the year. Existing historical testing creates selection risk; no forecast or proven edge claim.</p><p>The comparison harness uses a $1,000,000 execution balance so unrelated comparison legs do not exhaust shared margin, with separate hour magics. Statistics are rebased independently to $10,000, not compounded. Simultaneous order sequencing may differ slightly from running a single hour EA. No active-account orders or charts were changed. Preliminary M1 results had zero-spread artifacts and a collector/API boundary bid discrepancy; they are not used for headline performance.</p><div class="scroll">__AUDIT__</div></details>
<footer>Sources: broker historical quotes and native MT5 deal ledgers; all receipts, excluded positions and hashes are retained with this report. Review these tables before any optimisation or EA deployment.</footer></main><script>
const a=document.getElementById('asset'),w=document.getElementById('window'),sections=[...document.querySelectorAll('section')];function show(){sections.forEach(s=>s.hidden=s.dataset.asset!==a.value||s.dataset.window!==w.value)}a.addEventListener('change',show);w.addEventListener('change',show);document.getElementById('all').addEventListener('click',()=>sections.forEach(s=>s.hidden=false));show();
</script></body></html>'''
 output=template.replace('__TABLES__',''.join(sections)).replace('__CANDIDATES__',''.join(shortlist)).replace('__CONCLUSION__',conclusion).replace('__OVERNIGHT__',otable).replace('__AUDIT__',provenance)
 (R/'Results.html').write_text(output,encoding='utf-8')
 print(json.dumps({'tables':6,'rows':len(rows),'candidates':len(candidates),'positive_family_significant':len(positive_significant),'html_bytes':len(output.encode())}))
if __name__=='__main__':main()
