from pathlib import Path
import base64,html,json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parent
plt.rcParams.update({'figure.facecolor':'#091814','axes.facecolor':'#091814','axes.edgecolor':'#425b51','axes.labelcolor':'#d8ebe2','xtick.color':'#b4cdc1','ytick.color':'#b4cdc1','text.color':'#e8f8ef','grid.color':'#304b3e','font.size':10})
def fmt(v,dec=2):return '—' if v is None or (isinstance(v,float) and not np.isfinite(v)) else f'{v:,.{dec}f}'
def streak(v):
 a=b=ma=mb=0
 for z in v:a=a+1 if z>0 else 0;b=b+1 if z<0 else 0;ma=max(ma,a);mb=max(mb,b)
 return ma,mb
def main():
 raw=pd.read_csv(ROOT/'hourly-summary.csv');audit=json.loads((ROOT/'AUDIT.json').read_text());native=json.loads((ROOT/'NATIVE SUMMARY.json').read_text());normalized=[]
 for r in native:
  name=r['manifest']['window'];d=pd.DataFrame(json.loads((ROOT/'native'/name/'trades.json').read_text()));v=d.net_profit.to_numpy();gp=v[v>0].sum();gl=-v[v<0].sum();start=r['manifest']['start'].replace('.','-');end=r['manifest']['end'].replace('.','-')
  calendar=pd.bdate_range(start,pd.Timestamp(end)-pd.Timedelta(days=1)).strftime('%Y-%m-%d');daily=d.assign(date=d.close_time.str[:10]).groupby('date').net_profit.sum().reindex(calendar,fill_value=0).to_numpy();sh=daily.mean()/daily.std(ddof=1)*np.sqrt(252)
  mw,ml=streak(v);months=(pd.Timestamp(end)-pd.Timestamp(start)).days/365.2425*12
  normalized.append(dict(window=name,return_pct=float(v.sum()/100),net_cash=float(v.sum()),pf=float(gp/gl),win_rate_pct=float((v>0).mean()*100),equity_dd_pct=r['metrics']['max_relative_equity_drawdown_pct'],trades=len(v),daily_sharpe=float(sh),max_win_streak=mw,max_loss_streak=ml,commission=float(d.commission.sum()),swap=float(d.swap.sum()),trades_month=len(v)/months,trades_weekday=len(v)/len(calendar),history_quality=r['metrics']['history_quality']))
 # Native primary equity. No random-control comparison is claimed on this graph.
 d=pd.DataFrame(json.loads((ROOT/'native/5y/trades.json').read_text()));dates=pd.to_datetime(d.close_time);eq=10000+d.net_profit.cumsum();peak=np.maximum.accumulate(np.r_[10000,eq.to_numpy()])[1:];dd=(peak-eq)/peak*100
 fig,(ax,bx)=plt.subplots(2,1,figsize=(12,7),gridspec_kw={'height_ratios':[3,1]},sharex=True)
 ax.plot(dates,eq,color='#66efc2',lw=1.5);ax.axhline(10000,color='#8eaaa0',lw=.7);ax.set_title('11:00–12:00 New York • native MT5 closing balance');ax.set_ylabel('USD • fixed 1 USTEC lot');ax.grid(alpha=.35)
 bx.fill_between(dates,-dd,0,color='#ff8b86',alpha=.65);bx.set_ylabel('Closed DD %');bx.grid(alpha=.35);fig.tight_layout();fig.savefig(ROOT/'native-11-equity.png',dpi=160);plt.close(fig)
 five=raw[raw.window=='5y'].sort_values('hour');fig,ax=plt.subplots(figsize=(12,4.5));colors=['#66efc2' if x>0 else '#ff8b86' for x in five.mean_net_points];ax.bar(five.hour,five.mean_net_points,color=colors);ax.axhline(0,color='#adbeb5',lw=.7);ax.set_xticks(range(24));ax.set_xlabel('New York entry hour');ax.set_ylabel('Mean net index points');ax.set_title('All-hour M1 approximation • spread included, commission/financing excluded');ax.grid(axis='y',alpha=.35);fig.tight_layout();fig.savefig(ROOT/'hour-means.png',dpi=160);plt.close(fig)
 r=np.load(ROOT/'random-curves.npz',allow_pickle=True);dt=pd.to_datetime(r['dates']);fig,ax=plt.subplots(figsize=(12,4.5));ax.fill_between(dt,r['q05'],r['q95'],color='#6c94a0',alpha=.3,label='Matched random pointwise 5–95% band');ax.plot(dt,r['median'],color='#7bb4c3',label='Random median');ax.plot(dt,r['observed'],color='#66efc2',label='11:00 bar approximation');ax.set_title('Bar-price screen only • 2,000 same-date random-minute paths');ax.set_ylabel('Cumulative USD • $1/index point');ax.legend(facecolor='#10271e',labelcolor='#e8f8ef');ax.grid(alpha=.3);fig.tight_layout();fig.savefig(ROOT/'random-comparison.png',dpi=160);plt.close(fig)
 ntable='<table><thead><tr>'+''.join('<th>'+x+'</th>' for x in ['Window','Return','PF','Win rate','Equity DD','Trades','Daily Sharpe','Max W / L','Trades/month','Real-tick history'])+'</tr></thead><tbody>'
 md=['# US100 hourly raw test','', 'Primary result: 11:00–12:00 New York is weakly profitable, not a validated edge.','', 'Exness USTEC CFD; 2021-10-02 to 2026-10-02 exclusive. Fixed 1 lot, $10,000. No stop-loss. Native Model 4, 150ms. No live changes.','', '| Window | Return | PF | Win rate | Max equity DD | Trades | Daily Sharpe | Max W/L |','|---|---:|---:|---:|---:|---:|---:|---:|']
 for z in normalized:
  cells=[z['window'],fmt(z['return_pct'])+'%',fmt(z['pf'],3),fmt(z['win_rate_pct'])+'%',fmt(z['equity_dd_pct'])+'%',str(z['trades']),fmt(z['daily_sharpe']),f"{z['max_win_streak']} / {z['max_loss_streak']}",fmt(z['trades_month']),z['history_quality']]
  ntable+='<tr>'+''.join('<td>'+html.escape(x)+'</td>' for x in cells)+'</tr>'
  md.append(f"|{z['window']}|{fmt(z['return_pct'])}%|{fmt(z['pf'],3)}|{fmt(z['win_rate_pct'])}%|{fmt(z['equity_dd_pct'])}%|{z['trades']}|{fmt(z['daily_sharpe'])}|{z['max_win_streak']}/{z['max_loss_streak']}|")
 ntable+='</tbody></table>'
 atable='<table><thead><tr><th>NY hour</th><th>Trades</th><th>Net pts/trade</th><th>Win rate</th><th>PF</th><th>Raw p</th><th>Adjusted p</th><th>UTC-midnight holds</th></tr></thead><tbody>'
 for z in five.itertuples():
  cells=[f'{z.hour:02}:00–{(z.hour+1)%24:02}:00',str(z.trades),fmt(z.mean_net_points,3),fmt(z.win_rate_pct)+'%',fmt(z.pf,3),fmt(z.p_raw,4),fmt(z.p_adjusted_maxT,4),str(z.utc_midnight_crossings)]
  atable+='<tr>'+''.join('<td>'+html.escape(x)+'</td>' for x in cells)+'</tr>'
 atable+='</tbody></table>'
 primary=five[five.hour==11].iloc[0];best=five.sort_values('mean_net_points',ascending=False).iloc[0];checks=json.loads((ROOT/'VERIFICATION.json').read_text())
 inference=f"The 11:00 bar-price edge over matched random is {primary.mean_edge_points:.2f} points/hold. Its 95% five-date-block interval is [{primary.ci95_low:.2f}, {primary.ci95_high:.2f}]. Raw one-sided p={primary.p_raw:.4f}; adjusted max-T p={primary.p_adjusted_maxT:.4f} across {len(five)} hours. No hour survives the familywise 5% test. The descriptive leader is {int(best.hour):02}:00, not 11:00, with {best.mean_net_points:.2f} points/hold and PF {best.pf:.3f}. These p-values are from the bar approximation, not native tick execution."
 limits='Broker sessions and incomplete 60-minute windows leave 22 eligible hourly starts, not the video’s 23 NQ hours; 16:00 and 17:00 are unavailable under the frozen completeness rule. The random control uses the same date as each target trade, not freely selected dates. Overnight financing is omitted in the all-hour screen; UTC-midnight-crossing hours are flagged. Most older native data are generated ticks: only 15% real ticks across five years. Historical spread drops substantially in recent M1 data; native primary results include actual tester quotes, charged commission and execution delay. There is no SL, risk-% sizing, daily cap, portfolio simulation or live-account recommendation. Daily Sharpe is computed consistently from realised net daily cash changes including nontrade weekdays; it is not the MT5 report’s Sharpe calculation. Win rate and PF are recomputed from net closed deals; MT5’s gross Profit Trades count can differ when commission turns a flat or small positive trade into a loss.'
 md.extend(['','## Random comparison and hour search','',inference,'','## Limits','',limits,'','## Execution reconciliation',''])
 for z in normalized:md.append(f"- {z['window']}: native commission ${z['commission']:.2f}, swap ${z['swap']:.2f}; {z['trades_month']:.2f} trades/month, {z['trades_weekday']:.3f}/weekday.")
 md.extend(['','## Decision','','Stop for user review. No full pipeline, filter optimisation, production files, BATs or active account changed. ADX/DI scope next: shortlist only strategies for which trend strength, trend-direction agreement or low-trend regime has a testable rationale; preserve their current baseline and distinguish last 3/6/12 months from longer validation.'])
 (ROOT/'REPORT.md').write_text('\n'.join(md),encoding='utf-8');(ROOT/'NATIVE METRICS.json').write_text(json.dumps(normalized,indent=2))
 def img(p):return '<img alt="'+p.stem+'" src="data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()+'">'
 page='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Calyx • US100 hourly timing</title><style>body{margin:0;background:#07130f;color:#e9f6ee;font:16px system-ui;line-height:1.65}main{max-width:1250px;margin:0 auto;padding:44px 24px}h1{font-size:44px;line-height:1.13}h2{margin-top:36px}p{color:#b5cec2}.tag{color:#67efc1;letter-spacing:.12em;font-size:12px}.warning{border:1px solid #a68935;background:#27271a;padding:18px;border-radius:12px;color:#ffe28f}.box{background:#10221a;padding:22px;border:1px solid #2c493a;border-radius:15px;margin:20px 0}table{width:100%;border-collapse:collapse;font-size:13px}td,th{padding:12px;text-align:right;border-bottom:1px solid #2c4437;white-space:nowrap}td:first-child,th:first-child{text-align:left}th{color:#83b39c}.scroll{overflow:auto}img{width:100%;height:auto;border-radius:12px;margin:16px 0}.good{color:#67efc1}a{color:#67efc1}</style></head><body><main><div class="tag">CALYX • FROZEN RAW RESEARCH • 03 OCT 2026</div><h1>The 11am Nasdaq effect.<br>Profitable ≠ proven.</h1><p>Exness US100 (USTEC), New York clock with daylight-saving conversion. Five years through 1 October 2026. Fixed one lot on $10,000, not percentage risk.</p><div class="warning">RAW TEST ONLY • No stop-loss. This is not an approved FTMO strategy or a return forecast. No bot has been installed or changed.</div><h2>11:00–12:00 • native MT5 execution</h2><p>Model 4, 150ms execution delay. Spread and broker-charged commission included. Max DD is native floating-equity drawdown.</p><div class="box scroll">'''+ntable+'</div>'+img(ROOT/'native-11-equity.png')+'<h2>Does it beat random?</h2><p>'+html.escape(inference)+'</p>'+img(ROOT/'random-comparison.png')+'<h2>Every eligible hour • bar-price screen</h2><p>Separate from the native table above. Entry ask approximated using recorded M1 spread; exit bid open exactly 60 minutes later. Commission and financing excluded here.</p>'+img(ROOT/'hour-means.png')+'<div class="box scroll">'+atable+'</div><h2>What limits these results?</h2><p>'+html.escape(limits)+'</p><div class="box"><h2>Verification</h2><p>Seven unit tests passed; '+str(checks['verified_trades'])+' hourly ledger rows and '+str(checks['verified_summary_rows'])+' metric rows independently recomputed. Data and protocol hashes frozen. Native fills are verified separately against deals and the NY clock.</p></div><h2>Next step requires your review</h2><p>Stop here. Then shortlist suitable EAs for ADX-only, DI-only and combined filters, test against unchanged settings, and compare last 3/6/12 months with longer-history validation. No filter was promoted from this timing test.</p></main></body></html>'
 (ROOT/'Results.html').write_text(page,encoding='utf-8');print('\n'.join(md))
if __name__=='__main__':main()
