"""Render frozen simulation results and their limitations; no model fitting."""
import json,hashlib,math
from datetime import datetime,timezone
from prepare import ROOT,read,save

def money(x):return f'${x:,.2f}'
def table(headers,rows):
    return '\n'.join(['| '+' | '.join(headers)+' |','|'+'|'.join(['---']*len(headers))+'|']+['| '+' | '.join(map(str,r))+' |' for r in rows])
def main():
    data=read(ROOT/'results.json'); rr=data['results'];assert len(rr)==33
    sensitivity=read(ROOT/'sensitivity.json')['results'];assert len(sensitivity)==9
    audit=read(ROOT/'audit.json')
    grouped={}
    for r in rr:grouped.setdefault(r['plan']['name'],{})[r['months']]=r
    a='Raw + XAU/XAG news, $10/order';b='High-win + news'
    out=['# FTMO $10K Swing combination study — 19 September 2026',
         '**No credible, independently validated 70% future payout probability has been established.** The strongest tested news combinations cross 70% only at six months under this model. Their event presets were fitted to overlapping history, and actual FTMO news-straddle eligibility remains unresolved.',
         '## What was actually run',
         'Offline chronological shared-cash replay of saved native MT5 trade outcomes, then 1,000 joint-week bootstrap paths per portfolio, horizon and cost scenario. Eleven frozen combinations; 66,000 primary paths plus 9,000 two-week stress sensitivity paths. This is not a fresh synchronized FTMO tick backtest. No connected-account orders, chart deployment or risk changes were made.',
         'All comparisons end **2026-08-31 exclusive**. Two months: June 30–August 30; four months: April 30–August 30; six months: February 28–August 30. These are not windows ending today. The common bootstrap pool is 26 full weeks, March 2–August 30. Each horizon draws from that same pool; it is not a walk-forward forecast at its historical start date.',
         f"Audited {len(audit['eas'])} usable EA/mode variants; {len(audit['excluded'])} excluded for missing original-stop or cost evidence. Gold News V9 has no comparable five-year ledger and was not assigned fabricated performance. Non-news candidate screening uses pre-2024-09-19 history; the underlying strategies themselves were researched retrospectively.",
         '## Risk and account assumptions',
         '- Requested ordinary-entry risk: 5% / 7 = **0.7142857% = $71.43**, fixed to initial $10,000, not compounded. Lots round UP to 0.01, so actual planned loss can exceed this target. Gold raw in the regular production BAT still defaults to 1%; the FTMO research profile has not been installed.\n- Literal news comparison also requests $71.43 per side. Tight stops require too much gross margin when both sides are reserved, so this version admits no news baskets in the tested windows. Reduced-news alternatives explicitly use **$10 per side**, not $71.43. No opposite-side cancellation.\n- Maximum 7 daily entries, reserving slots for pending sides; stop new entries after 3 closed losses. Portfolio planned open/pending risk capped at $225, metals combined at $150.\n- Admission reserves a $300 daily loss budget (including costs and stressed stop allowances) and an internal $9,200 equity buffer. FTMO hard checks remain $500 daily and $9,000 total-equity floor. These admission checks can skip signals and are not the production news-exemption logic.\n- Margin: gold, silver and US100 1:15; FX 1:30; crypto conservatively 1:1. At most 80% of modeled equity allocated to gross reserved margin, without assumed hedging relief. Actual regional FTMO instrument specs must be verified.\n- 10% and 5% phase targets, 4 entry days per phase, Prague DST-aware midnight resets; assumed 2 and 5 business days phase administration. First funded trade starts a 14-day wait; request only flat, no pending orders, at least $25 gross profit. Initial payout split 80%, assumed 4 business days receipt. No evaluation profit withdrawal, fees/refunds/tax or subsequent payouts included.\n- A 30-day no-entry period during evaluation is classified separately as inactive, not as a loss breach. Calendar/admin assumptions are not promises from FTMO.',
         '## Cost and equity limitations',
         'Reference keeps native spread/gap fills, commission and swap, with explicit conservative fee floors. Stress reduces profitable gross outcomes by 10%, enlarges losses by 10%, adds asset-specific execution costs, and doubles negative swap or reserves additional carry. These are assumed stress costs, **not measured FTMO slippage**. The news sources are the fitted native reports, not evidence that the same returns are achievable at FTMO.',
         'Open equity is approximated by reserving every active position’s initial stop simultaneously: 1R ordinary / 1.25R news in reference, 1.25R / 2R under stress. This can reject viable trades and still miss larger gaps. Model drawdown is not observed intraday FTMO equity drawdown. Zero modeled breaches does not mean zero failure risk.',
         '## All combinations — modeled first payout receipt frequency',
         'Each cell is reference / execution-stress. This measures completion of both phases AND receipt of the first reward within the horizon, not merely hitting phase 1.',
         table(['Portfolio','2 months','4 months','6 months'],[[name]+[f"{v[m]['cases']['reference']['bootstrap']['payout_pct']:.1f}% / {v[m]['cases']['stress']['bootstrap']['payout_pct']:.1f}%" for m in (2,4,6)] for name,v in grouped.items()]),
         '## Preferred next validation candidate',
         '**Raw Gold Overnight Value Area + News Pulse XAU + News Pulse XAG**, with ordinary risk $71.43 and news risk $10/order, is the simpler research candidate. Adding RSI VWAP and Nasdaq Overnight raises the six-month one-week stressed payout frequency only from 78.8% to 79.1%, less than ordinary Monte Carlo sampling uncertainty; it is not evidence of superiority. Neither combination is approved here for a paid challenge.',
         'The five-EA high-win comparison consists of Raw Gold, XAU RSI VWAP Standard, Nasdaq Overnight Standard, News Pulse XAU and News Pulse XAG. The training-top-three are XAU Squeeze Momentum Standard, USDJPY London Open Momentum Standard and XAU Trend Progression Standard; top-five adds US100 ORB New York M30 and XAU Elliott Wave 1-2-3.',
         '## Shortlist — historical path, including challenge resets',
         'These are single observed paths, not probabilities. Statistics stop at the first reward request or failure; reward is shown only if its modeled receipt falls within the horizon.',
         table(['Portfolio','Months','Costs','Trades','WR','Best wins / losses','Model DD','Funded','Reward receipt','Reward USD','Breach'],[[name,r['months'],cost,h['trades'],f"{h['win_rate']:.1f}%",f"{h['max_win_streak']} / {h['max_loss_streak']}",f"{h['model_dd_pct']:.2f}%",(h['funded_at'] or 'No')[:10],(h['receipt_at'] if h['payout'] else 'No')[:10],money(h['reward'] if h['payout'] else 0),h['breach']] for name in (a,b) for r in grouped[name].values() for cost in ('reference','stress') for h in [r['cases'][cost]['historical']]]),
         'A stressed path can sometimes pay earlier or more than the reference path: changed admission and phase-transition dates select different subsequent trades. This is not a claim that worse execution improves the strategy.',
         '## Stress bootstrap detail',
         table(['Portfolio','Months','Funded','Payout received','Model breach','Inactive','Unfinished','Median trades','Median reward if paid','95th percentile model DD'],[[name,m,f"{s['funded_pct']:.1f}%",f"{s['payout_pct']:.1f}%",f"{s['breach_pct']:.1f}%",f"{s['inactive_pct']:.1f}%",f"{s['unfinished_pct']:.1f}%",s['median_trades'],money(s['median_reward_if_paid'] or 0),f"{s['p95_model_dd_pct']:.2f}%"] for name in (a,b) for m in (2,4,6) for s in [grouped[name][m]['cases']['stress']['bootstrap']]]),
         '## Two-week dependence sensitivity',
         table(['Portfolio','Months','Stressed payout frequency'],[[r['plan'],r['months'],f"{r['stress_two_week']['payout_pct']:.1f}%"] for r in sensitivity]),
         'Longer blocks preserve more consecutive wins/losses and regimes. These results still resample the same six-month history. A 1,000-path frequency near 79% has roughly ±2.5 percentage points of binomial Monte Carlo uncertainty; that does **not** include selection bias, data quality, broker behavior or changing markets.',
         '## Compliance gate and next steps',
         '1. Obtain written FTMO clarification for the exact pre-release two-sided straddle, tight stops and simultaneous XAU/XAG exposure. Swing permits ordinary news trading, but FTMO separately prohibits news-gap exploitation and excessive correlated trade-idea risk. No approval is assumed.\n2. Validate original signals and both pending directions on FTMO tick data, including actual contract sizes, fee schedule, margin, spread widening, gaps and rejected orders.\n3. Forward-test untouched settings and a shared-account risk controller. Treat the $71.43 and $10 alternatives as research until reviewed.\n4. Do not raise risk just to force a 70% headline. Two- and four-month stressed frequencies do not meet that target.',
         'Official rules: [Objectives](https://ftmo.com/en/trading-objectives/), [Swing](https://ftmo.com/en/faq/ftmo-swing-account-type/), [Rewards](https://ftmo.com/en/faq/how-do-i-withdraw-my-profits/), [Forbidden practices](https://ftmo.com/en/forbidden-trading-practices/). See PROTOCOL.md for margin/update references.',
         '## Audit files',
         '- `audit.json`: every screened mode, prior-period statistics and exclusions.\n- `prepared.json`: normalized source trades, original-stop provenance and placements.\n- `results.json`: all 33 horizon/portfolio combinations, both cost scenarios, historical and continuous-account ledgers, per-EA contribution, fees, rejections and bootstrap summaries.\n- `sensitivity.json`: nine two-week stress experiments.\n- `test_simulate.py`: deterministic accounting/risk/date regression checks.\n- `SOURCE MANIFEST.json`: hashes tying this report to inputs and engine.']
    (ROOT/'REPORT.md').write_text('\n\n'.join(out)+'\n',encoding='utf-8')
    names=['prepare.py','simulate.py','prepared.json','audit.json','plans-frozen.json','results.json','sensitivity.py','sensitivity.json','REPORT.md']
    save(ROOT/'SOURCE MANIFEST.json',dict(generated_at=datetime.now(timezone.utc).isoformat(),sha256={n:hashlib.sha256((ROOT/n).read_bytes()).hexdigest() for n in names}))
    print(table(['Portfolio','Months','Stressed payout','Historical payout','Trades','WR','Streak W/L','Model DD'],[[name,m,f"{s['bootstrap']['payout_pct']:.1f}%",money(h['reward'] if h['payout'] else 0),h['trades'],f"{h['win_rate']:.1f}%",f"{h['max_win_streak']}/{h['max_loss_streak']}",f"{h['model_dd_pct']:.2f}%"] for name in (a,b) for m in (2,4,6) for s in [grouped[name][m]['cases']['stress']] for h in [s['historical']]]))

if __name__=='__main__':main()
