# Generated by Django 5.2.17 on 2026-08-10 10:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_config", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("mt5_ea", "MT5 Expert Advisor"),
                            ("mt5_indicator", "MT5 Indicator"),
                            ("pine_strategy", "Pine Strategy"),
                            ("pine_indicator", "Pine Indicator"),
                        ],
                        max_length=32,
                    ),
                ),
                ("symbol", models.CharField(blank=True, default="EURUSD", max_length=32)),
                ("timeframe", models.CharField(blank=True, default="H1", max_length=16)),
                (
                    "description",
                    models.TextField(help_text="Describe the trading rules in plain language."),
                ),
                ("strategy_spec", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("ready", "Ready"), ("archived", "Archived")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workflow_snapshot", models.JSONField(blank=True, default=dict)),
                ("prompt", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("needs_input", "Needs input"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("current_step", models.CharField(blank=True, max_length=120)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=10),
                ),
                ("error_summary", models.TextField(blank=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generations",
                        to="ai_config.workflowdefinition",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generations",
                        to="builder.project",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CodeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("filename", models.CharField(max_length=180)),
                ("language", models.CharField(max_length=32)),
                ("source_code", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("assumptions", models.JSONField(blank=True, default=list)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("not_run", "Not run"),
                            ("passed", "Passed"),
                            ("warnings", "Passed with warnings"),
                            ("failed", "Failed"),
                        ],
                        default="not_run",
                        max_length=16,
                    ),
                ),
                ("diagnostics", models.JSONField(blank=True, default=list)),
                ("source_hash", models.CharField(blank=True, max_length=64)),
                (
                    "generation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="code_version",
                        to="builder.generation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_versions",
                        to="builder.project",
                    ),
                ),
            ],
            options={
                "ordering": ("-version",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "status", "-updated_at"], name="builder_pro_owner_i_30151c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generation",
            index=models.Index(
                fields=["project", "status", "-created_at"], name="builder_gen_project_94cc37_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="codeversion",
            constraint=models.UniqueConstraint(
                fields=("project", "version"), name="unique_project_version"
            ),
        ),
    ]
