# Generated by Django 5.2.17 on 2026-08-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeversion",
            name="compilation_status",
            field=models.CharField(
                choices=[
                    ("not_requested", "Not requested"),
                    ("not_applicable", "Not applicable"),
                    ("unavailable", "Compiler unavailable"),
                    ("passed", "Compiled"),
                    ("failed", "Compilation failed"),
                ],
                default="not_requested",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="codeversion",
            name="compiled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codeversion",
            name="compiler_output",
            field=models.TextField(blank=True),
        ),
    ]
