"""Offline evidence report; no external libraries, fonts or market data fetches."""
from pathlib import Path
import gzip,html,json
R=Path(__file__).resolve().parent
def load(p):return json.loads((R/p).read_text())
def main():
 rows=load('SUMMARY.json');mc=load('MONTE-CARLO.json');decisions=load('DECISIONS.json');selected=load('SELECTED-HOURS.json')['hours'];charts={}
 for row in rows:
  if row['variant']!='baseline':continue
  positions=json.loads(gzip.decompress((R/'native'/row['tag']/'positions.json.gz').read_bytes()));balance=10000;points=[[positions[0]['entry_epoch'],10000]]
  for trade in positions:balance+=trade['net_cash'];points.append([trade['exit_epoch'],round(balance,2)])
  # Keep min/max/end observations per UTC day: small offline report, not a
  # claim that every intraday point appears in a daily chart.
  groups={}
  for x in points:groups.setdefault(x[0]//86400,[]).append(x)
  thinned=[]
  for g in groups.values():
   keep={0,len(g)-1,min(range(len(g)),key=lambda i:g[i][1]),max(range(len(g)),key=lambda i:g[i][1])};thinned.extend(g[i] for i in sorted(keep))
  charts[row['tag']]=thinned
 data=json.dumps({'rows':rows,'mc':mc,'decisions':decisions,'selected':selected,'charts':charts},allow_nan=False).replace('</','<\\/')
 template=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Calyx · Hourly EA pipeline</title>
<style>:root{color-scheme:dark;--mint:#86fbd5;--muted:#9fb8b5;--line:#26453c;--red:#ff8992}*{box-sizing:border-box}body{margin:0;background:#08130f;color:#e9fff5;font:15px/1.6 system-ui,sans-serif}main{max-width:1450px;margin:auto;padding:36px 25px}h1{font-size:clamp(34px,5vw,64px);line-height:1.05;letter-spacing:-2px;margin:25px 0}h2{margin:30px 0 14px}h3{margin:8px 0}.eyebrow{color:var(--mint);font:12px monospace;letter-spacing:2px}.muted,p{color:var(--muted)}.warning{border:1px solid #806b31;background:#332f162f;padding:18px;border-radius:15px;color:#ffe99d;margin:20px 0}.card{background:linear-gradient(125deg,#14281e,#0c1b14);border:1px solid var(--line);border-radius:18px;padding:20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.toolbar{display:flex;gap:20px;align-items:end;flex-wrap:wrap;margin:24px 0}select,a.button{background:#132a20;border:1px solid #507868;color:#edfff6;border-radius:10px;padding:11px;font:inherit}a{color:var(--mint)}a.button{display:inline-block;text-decoration:none;margin:4px}.table{overflow:auto;border:1px solid var(--line);border-radius:14px}table{width:100%;border-collapse:collapse;white-space:nowrap}td,th{padding:11px 14px;text-align:right;border-bottom:1px solid var(--line)}td:first-child,th:first-child{text-align:left}th{color:var(--muted);font:11px monospace;text-transform:uppercase;background:#11231a}.good{color:var(--mint)}.bad{color:var(--red)}.big{font-size:30px;color:var(--mint)}svg{width:100%;height:auto;display:block}details{margin:15px 0}summary{cursor:pointer;color:var(--mint)}.pill{border:1px solid #7b6533;border-radius:20px;color:#fadd8a;font:11px monospace;padding:7px}.links{margin-top:15px}footer{color:var(--muted);font-size:12px;margin-top:35px}label{color:var(--muted);font-size:12px}label select{display:block;margin-top:4px}@media(max-width:900px){.grid{grid-template-columns:1fr}main{padding:20px 15px}td,th{padding:8px}}</style>
<main><div class="eyebrow">CALYX · FROZEN HOURLY PROFILES · 2026-10-03</div><h1>Eleven hours.<br>One EA. Three profiles.</h1><p>US30, US100 and SP500 · Native Exness CFD execution · $10,000 starting balance · One fixed CFD lot · New York time with daylight saving.</p>
<div class="warning"><b>RESEARCH ONLY — all three profiles failed the 3-/5-year raw gate.</b> Latest-year hours were selected using that same year's results. The year and quarter are not untouched holdout. No live installation or promotion. There is no SL: a one-hour planned exit is not a guaranteed maximum loss.</div>
<div class="links"><a class="button" href="CalyxHourlyProfiles.ex5" download>Compiled universal EA</a><a class="button" href="US30.set" download>US30 SET</a><a class="button" href="US100.set" download>US100 SET</a><a class="button" href="SP500.set" download>SP500 SET</a><a class="button" href="RULES.md">Rules / protocol</a><a class="button" href="MONTE-CARLO.json">Monte Carlo data</a></div>
<h2>Frozen schedules</h2><div class="grid"><div class="card"><h3>US30</h3><p>BUY 02:00, 06:00<br>SELL 00:00, 15:00, 22:00</p></div><div class="card"><h3>US100 / USTEC</h3><p>BUY 02:00, 13:00, 20:00<br>SELL 14:00, 22:00</p></div><div class="card"><h3>SP500 / US500</h3><p>SELL 22:00</p></div></div>
<p>Monday–Friday: enter in minute 00; close after 60 minutes. Failed or manually closed signals are not re-entered. Overdue positions block new entries. Broker sessions can delay closure, including across a weekend; those trades are retained. Static broker session definitions in historical testing may differ from the sessions in force at the historical date.</p>
<div class="toolbar"><label>Evidence window<select id="window"><option value="1y">2025-10-03 → 2026-10-03 · selection year</option><option value="3m">2026-07-03 → 2026-10-03 · selection quarter</option><option value="3y">2023-10-03 → 2026-10-03 · historical backcast</option><option value="5y">2021-10-03 → 2026-10-03 · historical backcast</option><option value="real2026">2026-01-01 → 2026-10-03 · real-tick segment</option></select></label></div>
<h2>Actual $10,000 native accounts</h2><div id="performance" class="table"></div><p>Net PF and win rate are recomputed from complete position P&L including commissions, swaps and fees. Sharpe uses daily net cash / initial capital with zero-trade weekdays. Equity DD is measured on the native tick path, not estimated from closed trades.</p>
<div id="charts" class="grid"></div><div class="card" style="margin-top:18px"><h3>All profiles — independent account comparison</h3><p>Each line starts at its own $10,000. This is <b>not a shared portfolio</b> and does not combine margins or exposure. Lines stop where the native account stopped.</p><div id="overlay"></div></div>
<h2>Every baseline horizon</h2><div id="allwindows" class="table"></div>
<h2>Hour-by-hour results</h2><div id="hours" class="table"></div><p>These are contributions to the combined profile. A stopped-out account cannot supply that hour's missing later trades. See the full-horizon diagnostic below; per-hour DD here is a closed-trade ledger rebased to $10k, not an isolated equity test.</p>
<h2>Monte Carlo — 10,000 paths per experiment</h2><div id="mc" class="table"></div><p>Latest-year day blocks preserve within-day trades; additive fixed-dollar P&L, blocks of 1 / 5 / 10 days. Intervals are conditional historical sensitivity, <b>not forecast returns or odds of future profitability</b>, and do not remove the hour-selection bias. MC drawdown is closed-P&L only. Five-year stop-out paths are not extrapolated over their missing remainder.</p>
<details><summary>Reshuffled streaks, missed trades and 5-year Monte Carlo</summary><div id="mc-extra"></div></details>
<h2>Timing and execution neighbors — not selected replacements</h2><div id="neighbors" class="table"></div><div id="costs"></div>
<h2>Full-horizon $1m execution-capital diagnostic</h2><p>The $10k US30/US100 runs stopped early. The following separate passes keep exactly one lot but use $1,000,000 so all selected hours can be inspected across the full 5 years. Returns below are <b>actual percentages of $1m</b>, not claims that $10k survived. These do not replace the baseline failures.</p><div id="coverage" class="table"></div><div id="coverage-hours" class="table" style="margin-top:18px"></div>
<details><summary>Calendar-year and monthly breakdown</summary><div id="calendar"></div></details>
<details><summary>Why the original hourly comparison differs</summary><p>The original table compared independent hourly cells on $1m execution capital and excluded incomplete or delayed holds afterwards. The universal EA uses all selected hours together on $10k, with one owned position at a time, known-session checks, actual delayed exits and no post-execution exclusions. Native windows start at midnight UTC, so the first evening trade may have the previous NY date. The complete ledgers and native report profits reconcile, including magic-zero broker-forced stop-outs recovered from native reports.</p></details>
<h2>Pipeline decisions</h2><div id="decisions"></div><footer>Model 4 · local isolated MT5 · 150ms baseline / 500ms delay stress · leverage 1:2000 · real ticks available from 2026-01-01; earlier history generated · fixed CFD multiplier $1 per index point per lot for these contracts, not an ES/NQ future · No genuinely untouched holdout or independent-broker validation. Approximate deflated-Sharpe screen counts at least 291 inspected comparisons/runs. Exact artifacts and hashes are retained. Does not update BATs, website catalogue or live charts.</footer>
</main><script>const DATA=__DATA__;
const assets=['US30','US100','SP500'],colors=['#86fbd5','#96baff','#f1ca7c'];
const n=(v,d=2)=>v===null||v===undefined?'Unavailable':Number(v).toFixed(d),pct=v=>n(v)+'%',sg=v=>(v>0?'+':'')+pct(v),money=v=>Number(v).toLocaleString('en-US',{style:'currency',currency:'USD'});
function table(head,rows){return '<table><thead><tr>'+head.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function perf(rows){return table(['Asset','Period / variant','Trades','Net PF','Win rate','Return','Net USD','Equity DD','Closed DD','Sharpe','Win / loss run','Late holds','Rejected checks','Status'],rows.map(r=>[r.asset,r.window+' / '+r.variant,r.trades,n(r.pf,3),pct(r.win_rate_pct),'<span class="'+(r.return_pct>0?'good':'bad')+'">'+sg(r.return_pct)+'</span>',money(r.net_cash),pct(r.equity_dd_pct),pct(r.closed_balance_dd_pct),n(r.sharpe_daily),r.max_win_streak+' / '+r.max_loss_streak,r.late_positions,r.execution_audit.checks_rejected,r.account_failure?'STOP-OUT '+r.last_exit_utc.slice(0,10):r.execution_audit.checks_rejected>0?'Margin/other checks blocked entries':'Completed']))}
function svg(series){const w=750,h=290,p=42;let pts=series.flatMap(x=>x.points);if(!pts.length)return '';const lo=Math.min(...pts.map(x=>x[1]),10000),hi=Math.max(...pts.map(x=>x[1]),10001),xmin=Math.min(...pts.map(x=>x[0])),xmax=1790985600;const x=t=>p+(t-xmin)/(xmax-xmin)*(w-2*p),y=v=>h-p-(v-lo)/(hi-lo)*(h-2*p);let s='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Closed trade balance">';for(let i=0;i<4;i++){let v=lo+(hi-lo)*i/3;s+='<line x1="'+p+'" y1="'+y(v)+'" x2="'+(w-p)+'" y2="'+y(v)+'" stroke="#26453c"/><text x="2" y="'+(y(v)+4)+'" fill="#9fb8b5" font-size="11">'+Math.round(v).toLocaleString()+'</text>'}series.forEach(z=>{s+='<polyline points="'+z.points.map(a=>x(a[0]).toFixed(1)+','+y(a[1]).toFixed(1)).join(' ')+'" fill="none" stroke="'+z.color+'" stroke-width="2"/>';let a=z.points.at(-1);s+='<circle cx="'+x(a[0])+'" cy="'+y(a[1])+'" r="3" fill="'+z.color+'"/>'});s+='<text x="'+p+'" y="'+(h-10)+'" fill="#9fb8b5" font-size="12">'+new Date(xmin*1000).toISOString().slice(0,10)+'</text><text x="'+(w-155)+'" y="'+(h-10)+'" fill="#9fb8b5" font-size="12">2026-10-03 exclusive</text></svg>';return s}
function hourTable(rows){let h=[];rows.forEach(r=>r.hour_breakdown.forEach(z=>h.push([r.asset,String(z.hour).padStart(2,'0')+':00 '+z.side,z.trades,n(z.pf,3),pct(z.win_rate_pct),money(z.net_cash),n(z.sharpe_daily),z.max_win_streak+' / '+z.max_loss_streak,z.late_positions])));return table(['Asset','NY hour / side','Trades','Net PF','Win rate','Net USD','Sharpe','Win / loss run','Late holds'],h)}
function render(){let w=document.querySelector('#window').value,rows=DATA.rows.filter(r=>r.variant==='baseline'&&r.window===w);document.querySelector('#performance').innerHTML=perf(rows);document.querySelector('#hours').innerHTML=hourTable(rows);document.querySelector('#charts').innerHTML=rows.map(r=>'<div class="card"><h3>'+r.asset+'</h3><div class="big">'+sg(r.return_pct)+'</div><p>Closed-trade balance · $10k start</p>'+svg([{points:DATA.charts[r.tag],color:colors[assets.indexOf(r.asset)]}])+'<p>Real-tick coverage: '+r.native_history_quality+'<br>Native equity DD '+pct(r.equity_dd_pct)+(r.account_failure?'<br><span class="bad">Stopped out '+r.last_exit_utc.slice(0,10)+'</span>':'')+'</p></div>').join('');document.querySelector('#overlay').innerHTML=svg(rows.map(r=>({points:DATA.charts[r.tag],color:colors[assets.indexOf(r.asset)]})))+'<p>'+assets.map((a,i)=>'<span style="color:'+colors[i]+'">'+a+'</span>').join(' · ')+'</p>';document.querySelector('#calendar').innerHTML=rows.map(r=>'<h3>'+r.asset+' — '+r.window+'</h3>'+table(['Year','Partial','Trades','Net USD','Return / initial','PF','Win rate'],r.annual.map(y=>[y.year,y.partial?'Yes':'No',y.trades,money(y.net_cash),sg(y.return_pct),n(y.pf,3),pct(y.win_rate_pct)]))+'<details><summary>Months</summary>'+table(['Month','Trades','Net USD','PF','Win rate'],r.monthly.map(y=>[y.month,y.trades,money(y.net_cash),n(y.pf,3),pct(y.win_rate_pct)]))+'</details>').join('')}
document.querySelector('#allwindows').innerHTML=perf(DATA.rows.filter(r=>r.variant==='baseline'));
document.querySelector('#mc').innerHTML=table(['Asset','Block days','Paths','Profitable historical resamples','Return P5 / P50 / P95','PF P5 / P50 / P95','Closed DD P95'],assets.flatMap(a=>DATA.mc[a]['1y'].day_blocks.map(b=>[a,b.block_days,b.paths,pct(b.probability_profit_pct),b.return_p05_p50_p95.map(sg).join(' / '),b.pf_p05_p50_p95.map(x=>n(x,3)).join(' / '),pct(b.closed_dd_p05_p50_p95[2])])));
document.querySelector('#mc-extra').innerHTML=assets.map(a=>{let b=DATA.mc[a]['1y'],f=DATA.mc[a]['5y'];return '<h3>'+a+'</h3>'+table(['Experiment','Result'],[['Reshuffle terminal return (constant)',sg(b.shuffle.terminal_return_pct_constant)],['Reshuffle closed DD P95',pct(b.shuffle.closed_dd_p05_p50_p95[2])],['Reshuffle win streak P5 / median / P95',b.shuffle.win_streak_p05_p50_p95.map(x=>n(x,0)).join(' / ')],['Reshuffle loss streak P5 / median / P95',b.shuffle.loss_streak_p05_p50_p95.map(x=>n(x,0)).join(' / ')],...b.missed.map(m=>['Miss '+pct(m.miss_rate*100)+' · return P5 / median / P95',m.return_p05_p50_p95.map(sg).join(' / ')])])+(f.status?'<p>'+f.reason+'</p>':table(['5y block','Return P5 / median / P95','PF P5 / median / P95'],f.day_blocks.map(z=>[z.block_days,z.return_p05_p50_p95.map(sg).join(' / '),z.pf_p05_p50_p95.map(v=>n(v,3)).join(' / ')])))}).join('');
document.querySelector('#neighbors').innerHTML=perf(DATA.rows.filter(r=>r.variant!=='baseline'&&r.variant!=='coverage1m'));
document.querySelector('#costs').innerHTML=DATA.decisions.map(d=>'<h3>'+d.asset+' cost sensitivity</h3><p>Extra surcharge '+money(d.friction.surcharge_per_trade)+' per trade, from P95 observed entry spread + adverse fill.</p>'+table(['Scenario','Net PF','Return','Win rate'],Object.entries(d.cost_stress).map(([k,v])=>[k,n(v.pf,3),sg(v.return_pct),pct(v.win_rate_pct)]))).join('');
let cov=DATA.rows.filter(r=>r.variant==='coverage1m');document.querySelector('#coverage').innerHTML=perf(cov);document.querySelector('#coverage-hours').innerHTML=hourTable(cov);
document.querySelector('#decisions').innerHTML=DATA.decisions.map(d=>'<div class="card"><h3>'+d.asset+' · '+d.verdict+'</h3>'+table(['Gate','Result'],Object.entries(d.gates).map(([k,v])=>[k.replaceAll('_',' '),'<span class="'+(v?'good':'bad')+'">'+(v?'PASS':'FAIL / NOT AVAILABLE')+'</span>']))+'<p>'+d.why_not_promoted+'</p></div>').join('');document.querySelector('#window').addEventListener('change',render);render();</script></html>'''
 template=template.replace('291 inspected','294 inspected')
 template=template.replace('<h2>Timing and execution neighbors — not selected replacements</h2>','<div class="warning">Historical spread limitation: many native entry bid/ask quotes have zero spread, even within the real-tick segment. Recorded tester costs are not proof of live cost realism. Extra measured-friction stress is shown below, but historical bid/ask integrity is unverified.</div><h2>Timing and execution neighbors — not selected replacements</h2><p>Holding 75 minutes can overlap the next selected hour. The one-position rule blocks that later entry; reduced trade counts are part of that variant, not a pure exit-only comparison.</p>')
 (R/'Results.html').write_text(template.replace('__DATA__',data),encoding='utf-8')
 lines=['# Hourly EA pipeline — 2026-10-03','','Research only. Fixed one-lot index CFDs, no SL; no live deployment.','', '| Asset | Period | Trades | PF | Win rate | Return | Native equity DD |','|---|---|---:|---:|---:|---:|---:|']
 for r in rows:
  if r['variant']=='baseline':lines.append(f"| {r['asset']} | {r['window']} | {r['trades']} | {r['pf']:.3f} | {r['win_rate_pct']:.2f}% | {r['return_pct']:+.2f}% | {r['equity_dd_pct']:.2f}% |")
 lines+=['','All three fail the long-window raw gate. Year and quarter were used for selection; not untouched holdout. US30/US100 5-year $10k accounts stopped out early. Full-period hour breakdown uses separate $1m execution diagnostics. Earlier ticks are generated; real ticks start 2026-01-01. Historical broker-session definitions may differ from actual historical availability. MC is conditional resampling, not a forecast.','','See Results.html, DECISIONS.json, MONTE-CARLO.json, native reports and reconciliation hashes.']
 (R/'RESULTS.md').write_text('\n'.join(lines)+'\n',encoding='utf-8');print('REPORT READY',R/'Results.html',flush=True)
if __name__=='__main__':main()
